### ISSUE TITLE
[Request] Open SpeechNote from Application Tray

### ISSUE THREAD

**Issue by WesleyFister** [mkiol/dsnote#100]
Perhaps I am missing something but currently if SpeechNote starts in the tray there is no way to open the gui again. You have to manually edit the config file to turn start_in_tray to false. I suggest adding a button to the tray icon to once again open the gui.

**Comment by mkiol** [comment]
That is surprising and definitely not intended.

I didn't test it on all possible systems, but in GNOME (tested on Ubuntu) and KDE Plasma (Ubuntu, Arch) to restore app window you just click on app icon in the tray. For instance on KDE Plasma, right mouse click on the tray icon shows menu with actions (Start listening,  Start reading, Quit...) but left mouse click shows app main window.

What is your distro and desktop environment?

**Comment by WesleyFister** [comment]
Sorry I should have mentioned that first. Here is the neofetch output.
![Screenshot from 2024-02-15 13-15-02](https://github.com/mkiol/dsnote/assets/112534696/33a98805-8098-449a-8cb6-24cc322d83f4)

In my case left and right clicking both bring up this menu.
![Screenshot from 2024-02-15 13-18-04](https://github.com/mkiol/dsnote/assets/112534696/727a8987-0bc7-4ce6-9263-a61cebee2508)

**Comment by WesleyFister** [comment]
So I didn't think to middle click the tray icon since I never use it... Apparently that is how you get it to open the main window. I think that changing this to be left clicking would be better since it would keep it more consistent across distributions. Anyways I'm going to close this issue now.

**Comment by mkiol** [comment]
Middle click :) I'm glad you find the solution. 

Still, I think it's a good idea to add an extra option to the tray menu to raise the app window.
