### ISSUE TITLE
"Processing" system tray icon, processing status

### ISSUE THREAD

**Issue by danboid** [mkiol/dsnote#102]
It would be good if SN displayed a processing icon like an hour glass or a clock icon or something in the system tray after it has stopped listening whilst it is processing the recording.

It would also be nice if the GUI (and maybe the system icon on mouse over?) would display some kind of progress indicator (in percent) when processing.

**Comment by mkiol** [comment]
> It would be good if SN displayed a processing icon like an hour glass or a clock icon or something in the system tray after it has stopped listening whilst it is processing the recording.

Yes. That would be useful. Thanks for the idea 👍🏿 

> display some kind of progress indicator (in percent) when processing

Unfortunately, STT engines don't provide progress information :/

**Comment by mkiol** [comment]
The new version 4.7.0 is out and available on flathub. 

The new version includes:

- Status indication in the system tray icon. When using the system tray icon, statuses such as processing, listening, etc. are presented with an animated tray icon.

Video demo: https://youtu.be/cEht4Fts6Bo?feature=shared&t=265
