### ISSUE TITLE
Enhancement: Hold to listen / Toggle listener in Global Shortcuts

### ISSUE THREAD

**Issue by jayma777** [mkiol/dsnote#112]
I love the "Text in Active Window" feature.  
Rather than / in addition to having a "Start Listening - text to active window" and "Stop Listening" as two separate shortcuts, it'd be nice to have a "toggle" setting.
As an example, pressing "Ctrl+Alt+Shift+T" toggles listening on / off. 
A "Hold to Listen" (Ctrl+Alt+Shift+H ?) similar to the option in the SN main window would be fantastic.

I'm not familiar with the languages this is coded in, or I'd jump in and create a Pull Request.

**Comment by mkiol** [comment]
Thanks for the idea. 

Indeed, what you suggested is much more convenient 👍🏿  I will try to change it in the upcoming update.

**Comment by mkiol** [comment]
New version 4.5.0 is out. It brings following change:

- Toggle option for keyboard shortcuts (X11 only). When <i>Toggle behavior</i> is enabled, Start listening/reading shortcuts will also stop listening/reading if they are triggered while listening/reading is active.

This <i>Toggle behavior</i> is enabled by default.

0467000ac82197f95b188a283ca1199281b923b0
