### ISSUE TITLE
(Request) Able to save generated audio (TTS) as MP3 or WAV

### ISSUE THREAD

**Issue by ghost** [mkiol/dsnote#113]
Best TTS GUI app for linux! Is it possible to save the generated audio as MP3 or WAV?

**Comment by Fadikkop** [comment]
I feel with you, SpeechNote is fantastic!
Yes, i can click on *File* and then *save Text as Audio* or something...
Is this so complicated?

**Comment by mkiol** [comment]
Thanks for "best" part :)

It is possible. Just use:

- `File` -> `Export to audio file` (v4.4.0), or
- `File` -> `Export to a file` -> `Export to audio file` (v4.5.0 beta)

**Comment by ghost** [comment]
Yes! It works!!
