### ISSUE TITLE
[FEATURE REQUEST] ability to change language and/or model using 1. tray right click context menu 2. global key shortcuts

### ISSUE THREAD

**Issue by hardpenguin** [mkiol/dsnote#114]
Hi! Once again great job with the app, I love it and it makes my day more accessible & productive.

I configured Speech Note in a way so I can quickly start listening or reading and copy to/from clipboard. For this purpose I use both global key shortcuts & hand-made icon launchers on my KDE panel (see attached picture).
![Screenshot_20240327_135526](https://github.com/mkiol/dsnote/assets/20478460/506c3e43-c3df-4977-a96c-c73a9e4c48b9)

Also, I use both English and Polish for my everyday computing activities.

- The issue starts when I want Speech Note to read the thing out loud in English instead of Polish or vice versa.
- Or when I want to make it listen in English but the currently selected behavior in the GUI is to listen in Polish.
- Both issues can be alleviated by changing the currently active model or voice from Polish to English or vice versa.

What would be helpful to me is to save myself a couple clicks and be able to switch between Polish & English model or voice with either:

1. tray icon -> right click -> context menu -> select model from the list or
2. global key shortcut to switch the model or voice

Of course it might be problematic to address it when the user has multiple models and/or voices installed (especially going for the solution nr 2 would be problematic in this scenario).

Looking forward to putting this on Speech Note's development roadmap. I undertand that as project owner & maintainer you might opt for a different solution completely. Or even disregard this request completely.

Keep up the good work!

**Comment by mkiol** [comment]
Hello! Thanks for the enhancement request.

> I configured Speech Note in a way so I can quickly start listening or reading and copy to/from clipboard. For this purpose I use both global key shortcuts & hand-made icon launchers on my KDE panel (see attached picture).

Smart! How did you make this "hand-made" launcher? Looks very handy indeed. Btw, under "right-click on taskbar icon menu" you have all possible actions, so I assume you needed something even more handy, right?

> tray icon -> right click -> context menu -> select model from the list or

I think I can add this to the upcoming release. Thank for the idea.

> global key shortcut to switch the model or voice

Maybe something like "switch-to-next-model" and "switch-to-prev-model" 🤔 I will check what can be done.

Recently I started more intensive tests on Wayland and sadly many of these "handy" features work only on X11. For instance on Wayland access to clipboard in not possible when app in the background (minimized for instance). If you are planning to migrate to Wayland, be warned that many things may be broken.

**Comment by hardpenguin** [comment]
> Smart! How did you make this "hand-made" launcher? Looks very handy indeed. Btw, under "right-click on taskbar icon menu" you have all possible actions, so I assume you needed something even more handy, right?

Correct! Those are just hand-crafted icons that launch commands respective to their global key shortcuts. So `J` is `--action start-listening-clipboard` and so on.

> I think I can add this to the upcoming release. Thank for the idea.

YAY!

> Maybe something like "switch-to-next-model" and "switch-to-prev-model" 🤔 I will check what can be done.

YAY! x2

> Recently I started more intensive tests on Wayland and sadly many of these "handy" features work only on X11. For instance on Wayland access to clipboard in not possible when app in the background (minimized for instance). If you are planning to migrate to Wayland, be warned that many things may be broken.

Ah yes, numerous Wayland regressions compared to X11. For now I stick to X11 until shooed away by some major transition in my distro.

Thank you for your replies!

**Comment by mkiol** [comment]
New version 4.5.0 is out and it brings following improvements:

- New <i>Actions</i> for STT/TTS models switching: <i>switch-to-next-stt-model</i>, <i>switch-to-prev-stt-model</i>, <i>switch-to-next-tts-model</i>, <i>switch-to-prev-tts-model</i>, <i>set-stt-model</i>, <i>set-tts-model</i>
- New global keyboard shortcuts for STT/TTS models switching (X11 only): <i>Switch to next STT model</i>, <i>Switch to prev STT model</i>, <i>Switch to next TTS model</i>, <i>Switch to prev TTS model</i>

7d52034e3b4f3587f462fd738a75e95982de9838
aa02c7827b0ebbf5a0354d63ffda6f9c55c073db
