### ISSUE TITLE
More human readable names in the audio source selector

### ISSUE THREAD

**Issue by alexschneider** [mkiol/dsnote#118]
Based off the conversation that’s recently happened in #57 I decided to raise an issue about a nit that has been bugging me for a long time, but hasn’t been a big deal. I often select different audio sources between my Bluetooth hearing aids, my laptop microphone, a plug in microphone, or various monitors. The audio sources, at least on my machine, are not intuitively named and it sounds like from the conversation in #57 that I’m not the only one. 

My hope is that one of a few options is possible (in rough order of preference)

1. Better names exist already in some metadata and can be displayed by speechnote (human readable hardware device name (manufacturer/model) and whether the source is a monitor or not). I’m fairly certain I’ve seen this in other programs. 
2. I can change the names in a durable fashion within my audio infrastructure and speechnote can either handle making that change in my system or provide advice on how to do so in the audio source selector
3. I can set a particular device ID within the speech note software to have a specific name and designate several options as favorites.

**Comment by mkiol** [comment]
Thanks for the report.

> 1. Better names exist already in some metadata and can be displayed by speechnote (human readable hardware device name (manufacturer/model) and whether the source is a monitor or not). I’m fairly certain I’ve seen this in other programs.

I think this can be done relatively easy. I will try to improve it the the next release.

**Comment by mkiol** [comment]
Fix: 0467000ac82197f95b188a283ca1199281b923b0

The fix is included in v4.5.0.

![image](https://github.com/mkiol/dsnote/assets/1420902/f1bb16b9-2940-43d2-8341-7a625938df18)
