### ISSUE TITLE
Read only selected text.

### ISSUE THREAD

**Issue by Bartosz2010** [mkiol/dsnote#129]
It would be useful to have the option to skip to the next fragment and/or read only selected text. Currently, the program reads the entire text entered, regardless of whether any fragment is selected or not.

**Comment by mkiol** [comment]
Hi. Thanks for the feature request.

Actually, it is already implemented and ready for tests in beta version (available on `flathub-beta` channel).

You can read selected text or read from (or to) cursor position.

![image](https://github.com/mkiol/dsnote/assets/1420902/c8b1cc48-a623-4161-af0c-cb1f7f1b84eb)

**Comment by Bartosz2010** [comment]
cool, this will make things easier
however, this function would also be useful for the Read button - you could create a condition that if nothing is selected, it reads as before, and if there is some text selected, it reads only what is selected

**Comment by mkiol** [comment]
To put it more simply, option "Read All" in the context menu. May be useful. Thanks for the idea.

**Comment by mkiol** [comment]
Change: 634f18d71c296358a1586c326dcfedb8c49f2b21

New version 4.5.0 is out and "Read selection" is included.
