### ISSUE TITLE
Start listening, text to active window not working

### ISSUE THREAD

**Issue by 31337-4554551n** [mkiol/dsnote#134]
When enabling accesibility, use of global keyboard shortcuts,
start listening, text to active window doesn't paste the text.

It starts listening, then when it stops the spoken text doesn't appear anywhere.

[edit] If the chosen window is a flatpak app, it works, fine. but not if it's trying to input into a deb installed software

Speechnote 4.4.0 flatpak
OS: Pop!_OS 22.04 LTS x86_64
DE: GNOME 42.9
GPU: AMD ATI 76:00.0 Rembrandt
GPU: AMD ATI Radeon RX 6700/6700 XT
Window system X11

**Comment by 31337-4554551n** [comment]
However if speechnote itself is the active window it works fine

**Comment by mkiol** [comment]
Thanks for reporting.

Yes, it's a common problem. From my observation it is not related to flapak/not-flatpak, but rather it just works perfectly for some apps and does not for other. I still didn't figure out what is root cause...

This feature uses "fake" X11 key strokes events to send text to external window. For some reasons, this method doesn't work always.

**Comment by 31337-4554551n** [comment]
Interesting, because for me it works on every flatpak app, and none of the non flatpak apps. Interesting coincidence if that's not the commonality.

**Comment by mkiol** [comment]
I need to make more tests. Maybe this "flatpak" is the right lead...

**Comment by 31337-4554551n** [comment]
Thank you, I really appreciate all the amazing work you're doing

**Comment by mruderman** [comment]
Thank you for developing, this has helped me tremendously!

I'm also running on pop OS 22.4. However, it has also worked on non-Flatpak apps as well, including my `Kate` text editor and proprietary Chrome browser that I'm writing this message in comma, which is not the flatpak wrapper version. 

My testing very informally and very limited seems that it works on most, actually all of the Qt based graphical programs I have, And really, kind of anything else that doesn't involve the Gnome desktop environment. This is very informal, but it It does not appear to be a flatpak vs non flatpak issue for PoP! PS 22.04 at least.

**Comment by chrstphmr** [comment]
Thank you for developing Speech Note!
I've encountered the same issue, here's my experience on Debian 12 with Xorg 7.7 and Xfce 4.18.

Working:

- Firefox (apt, GTK)
- qucs-s (apt, Qt)
- Zotero (flatpak, GTK)

Not Working:

- LibreOffice (apt, GTK)
- Gedit (apt, GTK)
- Gedit (flatpak, GTK)

At first glance, neither the GUI toolkit nor flatpak seem to be a clear culprit. 

Perhaps investigating the keyboard events using _xev_ could provide more insights? You can run xev -id <id> to monitor a specific window, and the ID can be obtained using _xwininfo_. I'll get back to this when I have more time.

**Comment by mkiol** [comment]
@chrstphmr Thanks for sharing the results. I can confirm that I can't run it with LibreOffice and Gedit either :/

So far, I have not found where the problem might be. I would be grateful for any tips if you have found a pattern when it works and when it doesn't.

**Comment by 31337-4554551n** [comment]
No luck with flatpak VS non flatpak? Cos that's the best lead I have. Very consistently works on all flatpak, and none of the debs.
It's interesting that you guys are getting a mix

**Comment by Benilerouge** [comment]
Same problem here, it works with Firefox and Featherpad, but it doesn’t with Thunderbird, Geany and SublimeText.

2 remarks:

1. I’m on MxLinux with XFCE. With Thunderbird, Geany and SublimeText, I noticed that when SpeechNote tries to write in the active window, the Workspace icon moves a little bit in the xfce-panel.
2. If we had an option to add a command after the execution of "Start Listening, text to clipboard", we could put something like "xdotool key ctrl+v" and the problem would be partially solved...

**Comment by lliurexia** [comment]
Perhaps you could research this repository, which can send text to any application:

[https://github.com/ideasman42/nerd-dictation]

Congratulations on this great tool. It would be perfect if it could solve the problem of sending text to any active window.

**Comment by mkiol** [comment]
@lliurexia Interesting. It looks that nerd-dictation uses external program [xdotool](https://github.com/jordansissel/xdotool) to do "key strokes sending". There is also a library `libxdo`, so it can be easily integrated into SpeechNote.

**Comment by mkiol** [comment]
Just pushed new [beta version](https://github.com/mkiol/dsnote/issues/179) to `flathub-beta` channel. This new beta has an option that allows you to change the method of sending keystrokes to `XDO`. It is not enabled by default, as I have not tested it extensively so far. This new method seems to work a bit slower, but it also works with `gedit` and most likely other apps that have had problems receiving "text to active window".

To enable go to `Settings`->`Advanced`->`X11`->`Fake keyboard type` and set it to `XDO`.

I would be grateful for your testing and feedback.

![image](https://github.com/user-attachments/assets/a3c68386-e918-4b94-9d07-f009c1553560)

**Comment by Benilerouge** [comment]
Tested... it works perfectly here, thank you so much!

**Comment by mkiol** [comment]
> it works perfectly here

Cool. Preparing official 4.7.0 release, and this fix will be included as default.

**Comment by mkiol** [comment]
The new version 4.7.0 is out and available on flathub. 

The new version includes "XDO" method as default.

Video presentation of all the new features introduced in version 4.7.0: https://www.youtube.com/watch?v=cEht4Fts6Bo

**Comment by 31337-4554551n** [comment]
> The new version 4.7.0 is out and available on flathub.
> 
> The new version includes "XDO" method as default.
> 
> Video presentation of all the new features introduced in version 4.7.0: https://www.youtube.com/watch?v=cEht4Fts6Bo

Thank you, this looks great.
I downloaded the latest release but moving the window while models are downloading (and possibly at other times, barely tested yet) crashes out my entire desktop.
Did it once, window kept changing size between 2 sizes (not maximised and regular, but regular and slightly bigger), and I could alt+f4 out. Second time I did it, killed the desktop, mouse moves, but nothing else.
Speechnote 4.7.0 flatpak
OS: Pop!_OS 22.04 LTS x86_64
DE: GNOME 42.9
GPU: AMD ATI 76:00.0 Rembrandt
GPU: AMD ATI Radeon RX 6700/6700 XT
Window system X11

**Comment by bitsByB** [comment]
Can I use Speech Note to fill out text in any window, I didn't find how to do it yet.
Using the flatpack version in wayland.
Thanks a lot!

![Image](https://github.com/user-attachments/assets/c6f2ecc7-eda8-463e-b157-7ef73f0ad2ac)

![Image](https://github.com/user-attachments/assets/f5d5f457-b174-40c6-88b9-4cbfbc7d4a76)

**Comment by szarma** [comment]
> Can I use Speech Note to fill out text in any window, I didn't find how to do it yet. Using the flatpack version in wayland. Thanks a lot!

From the screenshots you posted, it does not seem to be supported. I'm in the same boat. Did you figure out a workaround, @bitsByB ?

**Comment by bitsByB** [comment]
No, it seems it should be working in the next version though. You?

**Comment by mkiol** [comment]
Hello, sorry for the late reply. I missed the notification.

Yes, both "Global Keyboard Shortcuts" and "Insert into active window" works well on X11 right now but on Wayland will be supported in the upcoming v4.8.0. You can test it on `flathub-beta` channel. The "beta" version is actually done and I'm just focusing on testing and bug fixing now.

More info about v4.8.0 beta is here: https://github.com/mkiol/dsnote/issues/223
