### ISSUE TITLE
App stuck in tray icon

### ISSUE THREAD

**Issue by 31337-4554551n** [mkiol/dsnote#135]
Requesting to expand the "open to tray icon" feature.
If it opens to tray icon, there is no option in the menu to then open the full application again. Mine seems to be a permanent tray icon with no way to open the full app again.

Requesting both an
Open full app menu option from tray icon
Close to tray icon tickbox option in settings so that closing the main window keeps the app running in the tray.

Please help opening the full window again :( I can't figure it out

**Comment by 31337-4554551n** [comment]
Found ~/var/app/net/mkiol.SpeechNote/config/met.mkiol/dsnote/settings.conf

Changed
start_in_tray=false
start_in_tray=true

App opens again-but this doesn't seem ideal :P

**Comment by mkiol** [comment]
Thanks for the report.

It looks similar to this: https://github.com/mkiol/dsnote/issues/100. Maybe "middle" mouse click will help? :)

The new version has an additional “Show/Hide” menu option in the system tray to mitigate this problem.

**Comment by 31337-4554551n** [comment]
Middle click does indeed do the trick! I don't think that's written anywhere? Are there any more magic features?

I would still love a tickbox in settings to close to tray if you get the chance :)

**Comment by mkiol** [comment]
Actually, this "magic hidden feature" is a feature of PopOS, not Speech Note. On every other DE, single right click hides or rises the app window. The only exception appears to be PopOS. That is weird.
