### ISSUE TITLE
runtime org.kde.Platform branch 5.15-22.08 is end-of-life

### ISSUE THREAD

**Issue by 31337-4554551n** [mkiol/dsnote#136]
When running OS update, getting this error:

Info: runtime org.kde.Platform branch 5.15-22.08 is end-of-life, with reason:
   We strongly recommend moving to the latest Qt 5.15-based stable version of the Platform and SDK
Info: applications using this runtime:
   net.mkiol.SpeechNote

**Comment by mkiol** [comment]
Similar issue: https://github.com/mkiol/dsnote/issues/125

I'm planing to release new version this weekend. New version is based on newer Flatpak runtime.

**Comment by mkiol** [comment]
New Flatpak release is out. It is based on `org.kde.Platform/5.15-23.08` runtime.

https://github.com/flathub/net.mkiol.SpeechNote/commit/6c6bcb3e0e427e176eee307e7606a73483cccab1
