### ISSUE TITLE
Flatpak Add-ons are missing

### ISSUE THREAD

**Issue by mkiol** [mkiol/dsnote#139]
By mistake, a recent update to Flatpak add-ons made them impossible to find on the Flathub website, `flatpak search` and software stores.

**Comment by mkiol** [comment]
Fixes:
https://github.com/flathub/net.mkiol.SpeechNote.Addon.nvidia/pull/7
https://github.com/flathub/net.mkiol.SpeechNote.Addon.amd/pull/5

**Comment by mkiol** [comment]
Add-ons are not discoverable but still can be installed manually with:

```
flatpak install net.mkiol.SpeechNote.Addon.amd
```

or

```
flatpak install net.mkiol.SpeechNote.Addon.nvidia
```

**Comment by 31337-4554551n** [comment]
Showing interest, and confirming that even when installed manually, main software still gives the "a suitable graphics card cannot be found" error

**Comment by mkiol** [comment]
Problem has been resolved. Both add-ons are discoverable and updated in Flathub.
