### ISSUE TITLE
Add a good voice?

### ISSUE THREAD

**Issue by Ixel242** [mkiol/dsnote#140]
Hi!
I liked the Piper voices in Spanish that has Speech Note. By curiosity, I checked their website:
https://rhasspy.github.io/piper-samples/

... and I found interesting this voice (in Spanish too), 
es_ES-mls_10246-low 

Somehow, is it possible to add it to Speech Note?

Thank you in advance.

**Comment by mkiol** [comment]
Thanks for the report.

It looks that in 665c080fca4b7b89913ee48895e7943dbba2e897 I turned off all the MLS models! I don't remember exactly why, but most likely some MLS were broken and I disabled them all off for every languages without checking. 

I will re-enabled then in new version.

If you don't want to wait for a new version, you can enable it yourself by editing this file:
~/.var/app/net.mkiol.SpeechNote/data/net.mkiol/dsnote/models.json

Change `hidden` to `false` in:

```
        {
            "name": "Español (Piper MLS 10246 Low Female)",
            "model_id": "es_piper_es_mls10246_low",
            "engine": "tts_piper",
            "lang_id": "es",
            "checksum": "5ed4f42",
            "checksum_quick": "2e66d6bf",
            "comp": "dir",
            "urls": [
                "https://huggingface.co/rhasspy/piper-voices/resolve/a5400b9af996fd43eab8da0801c320629828f62a/es/es_ES/mls_10246/low/es_ES-mls_10246-low.onnx",
                "https://huggingface.co/rhasspy/piper-voices/resolve/a5400b9af996fd43eab8da0801c320629828f62a/es/es_ES/mls_10246/low/es_ES-mls_10246-low.onnx.json"
            ],
            "size": "63118672",
            "hidden": true
        },
        {
            "name": "Español (Piper MLS 9972 Low Female)",
            "model_id": "es_piper_es_mls9972_low",
            "engine": "tts_piper",
            "lang_id": "es",
            "checksum": "4632c099",
            "checksum_quick": "787d55da",
            "comp": "dir",
            "urls": [
                "https://huggingface.co/rhasspy/piper-voices/resolve/a5400b9af996fd43eab8da0801c320629828f62a/es/es_ES/mls_9972/low/es_ES-mls_9972-low.onnx",
                "https://huggingface.co/rhasspy/piper-voices/resolve/a5400b9af996fd43eab8da0801c320629828f62a/es/es_ES/mls_9972/low/es_ES-mls_9972-low.onnx.json"
            ],
            "size": "63118671",
            "hidden": true
        },
```

After app restart, you should be able to download `Español (Piper MLS 10246 Low Female)` and `Español (Piper MLS 9972 Low Female)`.

**Comment by Ixel242** [comment]
Thank you;
It isn't urgent, I can wait for  the next update.

If I try it, It will be because I like the challenges.

**Comment by Ixel242** [comment]
> Thanks for the report.
> 
> It looks that in [665c080](https://github.com/mkiol/dsnote/commit/665c080fca4b7b89913ee48895e7943dbba2e897) I turned off all the MLS models! I don't remember exactly why, but most likely some MLS were broken and I disabled them all off for every languages without checking.
> 
> I will re-enabled then in new version.
> 
> If you don't want to wait for a new version, you can enable it yourself by editing this file: ~/.var/app/net.mkiol.SpeechNote/data/net.mkiol/dsnote/models.json
> 
> Change `hidden` to `false` in:
> 
> ```
>         {
>             "name": "Español (Piper MLS 10246 Low Female)",
>             "model_id": "es_piper_es_mls10246_low",
>             "engine": "tts_piper",
>             "lang_id": "es",
>             "checksum": "5ed4f42",
>             "checksum_quick": "2e66d6bf",
>             "comp": "dir",
>             "urls": [
>                 "https://huggingface.co/rhasspy/piper-voices/resolve/a5400b9af996fd43eab8da0801c320629828f62a/es/es_ES/mls_10246/low/es_ES-mls_10246-low.onnx",
>                 "https://huggingface.co/rhasspy/piper-voices/resolve/a5400b9af996fd43eab8da0801c320629828f62a/es/es_ES/mls_10246/low/es_ES-mls_10246-low.onnx.json"
>             ],
>             "size": "63118672",
>             "hidden": true
>         },
>         {
>             "name": "Español (Piper MLS 9972 Low Female)",
>             "model_id": "es_piper_es_mls9972_low",
>             "engine": "tts_piper",
>             "lang_id": "es",
>             "checksum": "4632c099",
>             "checksum_quick": "787d55da",
>             "comp": "dir",
>             "urls": [
>                 "https://huggingface.co/rhasspy/piper-voices/resolve/a5400b9af996fd43eab8da0801c320629828f62a/es/es_ES/mls_9972/low/es_ES-mls_9972-low.onnx",
>                 "https://huggingface.co/rhasspy/piper-voices/resolve/a5400b9af996fd43eab8da0801c320629828f62a/es/es_ES/mls_9972/low/es_ES-mls_9972-low.onnx.json"
>             ],
>             "size": "63118671",
>             "hidden": true
>         },
> ```
> 
> After app restart, you should be able to download `Español (Piper MLS 10246 Low Female)` and `Español (Piper MLS 9972 Low Female)`.

Hi Mikol, 
Don't include these voices In the next update.... you were right, they are broken ... the voice sounds nice, but they start to do strange sounds and cuts that spoil the reading to speech.

Thank you!

**Comment by Ixel242** [comment]
Hi mkiol,

**Comment by mkiol** [comment]
Oh! Thanks for letting me know.

**Comment by mkiol** [comment]
New version v4.6.0 is out and I decided to include these voices, even if there is a problem with them. Maybe someone will find them useful for something...

The new version should be available in Flathub tomorrow.
