### ISSUE TITLE
Redirect text output to cursor ? [suggestion]

### ISSUE THREAD

**Issue by risoul** [mkiol/dsnote#142]
Thank you for that great tool. Works great for me on ubuntu with whisper base.

Is it possible to redirect the text output from the application to the cursor? 
With Nerd dictation, there is no need of copy/paste the text. When it runs, the text is showing directly where the cursor is.
You put the cursor where you want to type, start dictation and the text is showing without windows switching.

Usage example:

- Without redirected text
I am on gmail and want to answer a mail.
I have to open the dsnote window, press dictate, dictate, copy the text, paste it back in gmail.

- With redirected text
I am on gmail and want to answer a mail
I push the keyboard shortcut to start dictation
The text appear directly on my gmail page, no need to copy paste or windows switching

**Comment by risoul** [comment]
Sorry, I just realize that it is already possible using the "text to active window" shortcut ! perfect !

**Comment by mkiol** [comment]
I'm glad you found it. I must admit that “text to active window” is quite flawed and does not work in all cases. If you test it I would like to know your opinion.

**Comment by sirweazel** [comment]
> Sorry, I just realize that it is already possible using the "text to active window" shortcut ! perfect !

where did you find the "text to active window" option. I'm running the flatpack under gnome (fedora) running speech note 4.5.0, but i don't see this option. I'm sure i'm over looking it, but if you could point me in right direction of screenshot?

**Comment by sirweazel** [comment]
For anyone looking, it took me awhile to find it. I had to enable system tray icon in the settings menu, then from the system tray you have additional functionality.

**Comment by mkiol** [comment]
> For anyone looking, it took me awhile to find it. I had to enable system tray icon in the settings menu

Actually, "tray icon" is not needed. This "text to active window" can be invoked via key shortcut or via command line "action". 

I must admit, this feature isn't well "advertised" because it doesn't work always. In many cases the text is not inserted to active window.

![image](https://github.com/mkiol/dsnote/assets/1420902/bb5c0145-a395-4f78-8e1c-666f8a75e472)
![image](https://github.com/mkiol/dsnote/assets/1420902/da37211c-0ce0-4880-a5ed-61800ab6c44a)
