### ISSUE TITLE
UX request: provide a button to swap languages (for translator)

### ISSUE THREAD

**Issue by Flimm** [mkiol/dsnote#143]
In the translator tab, you can set the left side to one language (say English), and the right side to another language (say Italian):

    English | Italian

It would be useful to have a button to swap the languages like this:

    Italian | English

As I was typing this issue, I realised that Speech Note does provide this functionality already, using the "Replace" button that appears only once a translation is made. I'm more used to the design that you can find in [Google Translate](https://translate.google.co.uk/?sl=auto&tl=en&op=translate) or [Reverso Context](https://context.reverso.net/translation/english-italian/hello). Those things provide a button, labelled with two arrows, each pointing in the other direction, with the tooltip "Swap languages" or "Change language direction". This button is in between the two language controls. This button is always visible, even before the first translation is made. It also is visible even after the text boxes are emptied. The label "Replace" was not clear to me, I did not realise until now that it swapped languages.

This is an amazing application, thank you for taking the time to make all this open source work available to users like me.

**Comment by Flimm** [comment]
Another piece of feedback. Let's say my language set up is like this in the Translator tab:

    English | Italian
    
If I click on the left language selection box, and select Italian, it would be handy if the language selection box on the right would change to English. That way, the languages would get swapped. What happens instead is that the language selector on the right changes automatically to the first non-English language, for example, French. I think it is more likely that the user is trying to swap the languages than trying to select the first language on the list to the right. For that reason, it would be good if the code chose it automatically.

**Comment by mkiol** [comment]
Hi. Thanks a lot for the UX tips!

I have to admit that I am very bad at user interface design. That's what makes this whole application so ugly and difficult to use. Thanks to suggestions like yours I can see what can be improved.

Both suggestions are absolutely right. I will try to improve the lang swapping in the next version.

**Comment by mkiol** [comment]
Just letting know that translator UI has been improved in the latest Beta version. Also "Language swapping" works as you suggested.

![image](https://github.com/user-attachments/assets/18becf31-62a2-403a-816c-d0f1210a9250)

If you'd like to test the beta version, here's the [full change log](https://github.com/mkiol/dsnote/issues/145).

**Comment by Flimm** [comment]
Wonderful! I look forward to trying it.

**Comment by mkiol** [comment]
Thanks once again for great UX tips! Both changes are included in v4.6.0. The new version should be available in Flathub tomorrow.

Changes: ecb74e5b0719f65e3f87743c42d1e3170fd242fa 161c654762344543b7300d64889ca8c7f791a43b

**Comment by Flimm** [comment]
I tried it out and it works beautifully. Thank you!

**Comment by mkiol** [comment]
Cool. I'm glad I could make it better :)
