### ISSUE TITLE
can't build under Fedora 40

### ISSUE THREAD

**Issue by amindomao** [mkiol/dsnote#144]
After long time make'ing I've got an error which I can't find any clues to solve to. Give me please some that clues.

```
make[6]: *** [Makefile:479: encode.lo] Error 1
make[5]: *** [Makefile:371: all-recursive] Error 1
make[4]: *** [Makefile:428: all-recursive] Error 1
make[3]: *** [Makefile:352: all] Error 2
make[2]: *** [CMakeFiles/openfst.dir/build.make:86: openfst-prefix/src/openfst-stamp/openfst-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:485: CMakeFiles/openfst.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by mkiol** [comment]
Hi. Thank for trying to build Speech Note.

The problem you observed is with building of dependencies for `libvosk`. You can "skip" this step by using `-DBUILD_VOSK=OFF -DDOWNLOAD_VOSK=ON`. 

Actually, I recommend starting with all of the following options and possibly removing some of them if necessary later:

`-DWITH_DESKTOP=ON -DBUILD_VOSK=OFF -DDOWNLOAD_VOSK=ON -DBUILD_WHISPERCPP_CUBLAS=OFF -DBUILD_WHISPERCPP_HIPBLAS=OFF -DBUILD_WHISPERCPP_CLBLAST=OFF -DBUILD_OPENBLAS=OFF`

You may also check how [Arch package](https://github.com/mkiol/dsnote/blob/main/arch/git/PKGBUILD) is built. 

Speech Note has also runtime dependencies for Qt5 stuff. For example for Ubuntu, the following packages has to be installed to be able to run the app:

-   qml-module-org-kde-qqc2breezestyle
-   qml-module-org-kde-qqc2desktopstyle
-   qml-module-org-kde-quickcharts
-   qml-module-qtquick-controls
-   qml-module-qtquick-dialogs

Good luck :)

**Comment by lamyergeier** [comment]
> Speech Note has also runtime dependencies for Qt5 stuff. For example for Ubuntu, the following packages has to be installed to be able to run the app:
>    qml-module-org-kde-qqc2breezestyle
>    qml-module-org-kde-qqc2desktopstyle
>    qml-module-org-kde-quickcharts
>    qml-module-qtquick-controls
>    qml-module-qtquick-dialogs


@mkiol On Fedora 40 following packages are available for `qml`. What should I do as I am not sure if above dependencies will be fullfilled by any of the following:

```
$ dnf search qml
Last metadata expiration check: 0:15:52 ago on Tue 02 Jul 2024 17:01:11 CEST.
========================= Name & Summary Matched: qml ==========================
accounts-qml-module-doc.noarch : Documentation for accounts-qml-module
accounts-qml-module-qt5.x86_64 : Qt5 build of accounts-qml-module
accounts-qml-module-qt6.x86_64 : Qt6 build of accounts-qml-module
python3-doxyqml.noarch : Doxygen to document your QML classes
qmltermwidget.x86_64 : A port of QTermWidget to QML
qtav-qml-module.x86_64 : QtAV QML module
snapd-qt-qml.x86_64 : Library providing a Qt6 QML interface to snapd
vim-syntastic-qml.noarch : A syntax checker for qml programming language
============================== Name Matched: qml ===============================
mingw32-qt5-qmldevtools.x86_64 : Qt5 for Windows build environment
mingw32-qt5-qmldevtools-devel.x86_64 : Qt5 for Windows build environment
mingw64-qt5-qmldevtools.x86_64 : Qt5 for Windows build environment
mingw64-qt5-qmldevtools-devel.x86_64 : Qt5 for Windows build environment
qmlkonsole.x86_64 : Terminal app for Plasma Mobile
============================= Summary Matched: qml =============================
gsettings-qt.x86_64 : Qt/QML bindings for GSettings
gstreamer1-plugins-good-qt.x86_64 : GStreamer "good" plugins qt qml plugin
gstreamer1-plugins-good-qt6.x86_64 : GStreamer "good" plugins qt6 qml plugin
haruna.x86_64 : Open source video player built with Qt/QML and libmpv
kf5-qqc2-desktop-style.x86_64 : QtQuickControls2 style for consistency between QWidget and QML apps
kf6-qqc2-desktop-style.x86_64 : QtQuickControls2 style for consistency between QWidget and QML apps
libmpris-qt5.x86_64 : Qt and QML MPRIS interface and adaptor
mpvqt.x86_64 : QML wrapper for libmpv
qqc2-desktop-style.x86_64 : QtQuickControls2 style for consistency between QWidget and QML apps
qt5-qt3d.x86_64 : Qt5 - Qt3D QML bindings and C++ APIs
qt6-qt3d.x86_64 : Qt6 - Qt3D QML bindings and C++ APIs
qtav-players.x86_64 : QtAV/QML players
sddm.x86_64 : QML based desktop and login manager
```

**Comment by mkiol** [comment]
You will definitely have to install these and all their dependencies to be able to run the app:

- qqc2-desktop-style
- kf5-qqc2-desktop-style

I must admit I know almost nothing about Fedora package system, so can't help much.

To make successful build you don't need them. They are only needed to run the already built app. 

Just curious, did you manage to go through the steps of `cmake` and `make`?

**Comment by mkiol** [comment]
Please re-open if you need more information.
