### ISSUE TITLE
Add reading speed and esport audio in other format.

### ISSUE THREAD

**Issue by albanobattistella** [mkiol/dsnote#15]
HI,
thanks for this awesome APP.
Very useful for students and teachers and for students with some problems.
I would suggest entering various reading speeds when text is read.
Also, the ability to export audio to other formats like MP3,ogg,etc.
Thank you.
V/R,
A.

**Comment by mkiol** [comment]
Thanks for the ideas.

Adding to the roadmap:

- option to change reading speed for TTS 
- export to MP3 and other popular audio formats

**Comment by albanobattistella** [comment]
> Thanks for the ideas.
> 
> Adding to the roadmap:
> 
>     * option to change reading speed for TTS
> 
>     * export to MP3 and other popular audio formats

Hi,
thanks to you!  :-)

**Comment by mkiol** [comment]
0678d621fff57caaef69f001306c22f60cad5497

**Comment by mkiol** [comment]
- [x] option to change reading speed for TTS (0678d621fff57caaef69f001306c22f60cad5497)
- [x] save to MP3 and OGG audio formats (9051f35cfc4b9732ebc0a3e6273cad3c608925a0)

**Comment by mkiol** [comment]
Implemented in version 4.2.0

0678d621fff57caaef69f001306c22f60cad5497
9051f35cfc4b9732ebc0a3e6273cad3c608925a0

**Comment by albanobattistella** [comment]
> Implemented in version 4.2.0
> 
> [0678d62](https://github.com/mkiol/dsnote/commit/0678d621fff57caaef69f001306c22f60cad5497) [9051f35](https://github.com/mkiol/dsnote/commit/9051f35cfc4b9732ebc0a3e6273cad3c608925a0)

HI, 
thanks! 
Is it possible to have the .deb package in addition to flatpack?
Regards,
A.

**Comment by mkiol** [comment]
> Is it possible to have the .deb package in addition to flatpack?

I'm thinking about it. Most likely yes but not very soon. 

https://github.com/mkiol/dsnote/issues/34

**Comment by albanobattistella** [comment]
> > Is it possible to have the .deb package in addition to flatpack?
> 
> I'm thinking about it. Most likely yes but not very soon.
> 
> #34

Hi,
Thanks!
Thank you for the wonderful program which will be very useful at school.
I wanted to suggest putting the speech speed in the first interface below reading.
This is to avoid having to enter the settings every time I change the reading speed.
This is very useful for students and people with dyslexia or other problems.
Thanks again!
Best Regards,
Albano

**Comment by mkiol** [comment]
> I wanted to suggest putting the speech speed in the first interface below reading.
This is to avoid having to enter the settings every time I change the reading speed.

👍🏿
