### ISSUE TITLE
Add whisper-large-v3-turbo STT model

### ISSUE THREAD

**Issue by JamesClarke7283** [mkiol/dsnote#165]
just a FYI, OpenAI released a new version of Whisper Large V3, which is faster than the original model with minimal performance degradation, consider adding it:

[Whisper Large V3 Turbo HF Link](https://huggingface.co/openai/whisper-large-v3-turbo)

**Comment by mkiol** [comment]
Cool :)

Large-v3 Turbo model added both for WhisperCpp and FasterWhisper in 1d971941e2c2019027b12513e6f9c2d0a31140b0. 

Observations: It is faster ~10% but doesn't support "Translate to English" feature.

**Comment by mkiol** [comment]
Added in 1d971941e2c2019027b12513e6f9c2d0a31140b0, but not yet released in official version.

You can test Turbo models (and other improvements) by installing Beta version. More details can be found [here](https://github.com/mkiol/dsnote/issues/179).

**Comment by mkiol** [comment]
The new version 4.7.0 is out and available on flathub. 

The new version includes:

- New _Whisper Large Turbo_ model for both _WhisperCpp_ and _FasterWhisper_.

Video presentation of all the new features introduced in version 4.7.0: https://www.youtube.com/watch?v=cEht4Fts6Bo
