### ISSUE TITLE
speechnote says no-models-found when looking for text-to-speech

### ISSUE THREAD

**Issue by crowlogic** [mkiol/dsnote#171]
![Screenshot from 2024-10-16 00-35-42](https://github.com/user-attachments/assets/0a4f4631-7d78-4134-b3ea-2bf3610839b7)

whats up with that?

**Comment by mkiol** [comment]
Hi. Thanks for reporting.

Could you please start the app with `--verbose` option to collect more logs?

```
flatpak run net.mkiol.SpeechNote --verbose
```

**Comment by linlinxza** [comment]
> Hi. Thanks for reporting.
> 
> Could you please start the app with `--verbose` option to collect more logs?
> 
> ```
> flatpak run net.mkiol.SpeechNote --verbose
> ```

I ran that command. This is what I get:

```
[D] 00:29:53.791051033.791 0x741282dc8d00 () - download_progress: "en" 0.0102159
[D] 00:29:54.902947480.902 0x741282dc8d00 () - download_progress: "en" 0.0211398
[D] 00:29:56.017503527.17 0x741282dc8d00 () - download_progress: "en" 0.0318925
[D] 00:29:56.928862248.928 0x741282dc8d00 () - download_progress: "en" 0.0422031
[D] 00:29:57.259563201.259 0x74126cc00680 () - total downloaded size: 0
[W] 00:29:57.259705051.259 0x74126cc00680 () - checksum 1 is invalid: "0" (expected "6d38ae6e" )
[D] 00:29:57.259715108.259 0x74126cc00680 () - quick checksum 1: "0"
[D] 00:29:57.261514324.261 0x741282dc8d00 () - default stt model not found: "en"
[D] 00:29:57.261528642.261 0x741282dc8d00 () - default tts model not found: "en"
[D] 00:29:57.261535696.261 0x741282dc8d00 () - default mnt lang not found: "en"
[D] 00:29:57.261542261.261 0x741282dc8d00 () - new default mnt lang: "en"
[D] 00:29:57.261770996.261 0x741282dc8d00 () - service refresh status, new state: not-configured
[D] 00:29:57.262109523.262 0x741282dc8d00 () - stt models changed
[D] 00:29:57.262224414.262 0x741282dc8d00 () - update listen
[D] 00:29:57.262251583.262 0x741282dc8d00 () - tts models changed
[D] 00:29:57.262308225.262 0x741282dc8d00 () - update listen
[W] 00:29:57.262324429.262 0x741282dc8d00 () - no available tts models for in mnt
[W] 00:29:57.262329737.262 0x741282dc8d00 () - no available tts models for out mnt
[D] 00:29:57.262334975.262 0x741282dc8d00 () - ttt models changed
[D] 00:29:57.265007922.265 0x741282dc8d00 () - mnt langs changed
[D] 00:29:57.265050037.265 0x741282dc8d00 () - update listen
[W] 00:29:57.265064285.265 0x741282dc8d00 () - no available mnt langs
[W] 00:29:57.265069942.265 0x741282dc8d00 () - no available mnt out langs

```

I can click on any language model to download them and almost none of them download. I just get an error saying that it can't download.

And if it successfully downloaded, I get this:
```

[W] 00:33:51.396856673.396 0x74113f400680 () - checksum 1 is invalid: "0" (expected "9f357324" )
[D] 00:33:51.396864146.396 0x74113f400680 () - quick checksum 1: "0"
[D] 00:33:51.398183122.398 0x741282dc8d00 () - default stt model not found: "en"
[D] 00:33:51.398197021.398 0x741282dc8d00 () - default tts model not found: "en"
[D] 00:33:51.398201770.398 0x741282dc8d00 () - default mnt lang not found: "en"
[D] 00:33:51.398207358.398 0x741282dc8d00 () - new default mnt lang: "en"
```

I can't download any language models. So, I can't use this application until this issue is resolved.

**Comment by mkiol** [comment]
This is super weird 🤔 

Could you please re-install and delete app data. This can be done with the following commands:

```
flatpak uninstall net.mkiol.SpeechNote --delete-data
flatpak install net.mkiol.SpeechNote
```

If the problem persists, paste the full log of the app launch here.

**Comment by linlinxza** [comment]
> This is super weird 🤔
> 
> Could you please re-install and delete app data. This can be done with the following commands:
> 
> ```
> flatpak uninstall net.mkiol.SpeechNote --delete-data
> flatpak install net.mkiol.SpeechNote
> ```
> 
> If the problem persists, paste the full log of the app launch here.

Seems like deleting the app data fixed it. But also, it seems like my PiHole server was blocking access to `coqui.gateway.scarf.sh`. So, I whitelisted that. I block a lot of shit on the Internet (from much of big tech, to mainstream social media and other trash). 😅

Seems like it's fixed for me.

**Comment by mkiol** [comment]
Cool! I'm super glad you fixed it :)

> PiHole server was blocking access to coqui.gateway.scarf.sh

Yes, this is a [Coqui](https://coqui.ai/) proxy that always redirects to Github URLs. I probably need to rewrite these links to direct links to Github. It is very sad but Coqui is shutting down and this proxy may no longer work.

**Comment by linlinxza** [comment]
> Cool! I'm super glad you fixed it :)
> 
> > PiHole server was blocking access to coqui.gateway.scarf.sh
> 
> Yes, this is a [Coqui](https://coqui.ai/) proxy that always redirects to Github URLs. I probably need to rewrite these links to direct links to Github. It is very sad but Coqui is shutting down and this proxy may no longer work.

Honestly, it's sad that the more people use the Internet, the more it's turning to shit with the constant enshittification. Which is why I have to go to such extremes to filter the crap out with a PiHole server (along with my own hosted search engine by using SearXNG with link filtering as well).

Anyway, I am going to be using this program again at some point. And I am going to try dictation. Right now, I am just writing on paper to get my thoughts out.

**Comment by crowlogic** [comment]
I love it, we need more rants that tell it like it is

**Comment by linlinxza** [comment]
> I love it, we need more rants that tell it like it is

Glad you agree. Now, if the rest of the masses didn't waste their lives on such brain rot online (AKA social media). Then we'd be back in a better place.

**Comment by crowlogic** [comment]
I agree I don't have a social media whatever that is. I only know know that
actual social interaction sometimes it happens in a place known as the
world or reality or over there. I have a working theory that Facebook has
been more detrimental society than the production of crack cocaine and
heroin combined. Zuckerberg is more guilty than El Chapo

**Comment by linlinxza** [comment]
> I agree I don't have a social media whatever that is. I only know know that actual social interaction sometimes it happens in a place known as the world or reality or over there. I have a working theory that Facebook has been more detrimental society than the production of crack cocaine and heroin combined. Zuckerberg is more guilty than El Chapo

All of Meta (Instragram etc), Twitter (now X), Tiktok, and Youtube, has done a number to people's psyche. For this reason, I am glad I blocked all of it; except Youtube (on the PiHole) as other people watch it. Thankfully, they don't use anything else (nor engage with others on such brain rot platforms). It's bad enough watching people walking down the street with their heads looking at their phones while walking and almost getting hit by vehicles due to being so unaware of their surroundings.

Anyway, I use Odysee and Peertube and get RSS feeds from those and can view videos through the RSS guard application. So, I hardly have a reason to open a web browser anymore.

**Comment by crowlogic** [comment]
Hi I swear I'm not just feeling extra agreeable today but I usually agree
YouTube does not count as social media My well my unified theory will
actually show that many of Terence McKenna's statements were more than just
metaphors probably

**Comment by crowlogic** [comment]
> "Hey. If any of you are looking for any last-minute gift ideas for me, I
have one. I'd like Frank Shirley, my boss, right here tonight. I want him
brought from his happy holiday slumber over there on Melody Lane with all
the other rich people, and I want him brought right here... with a big
ribbon on his head! And I want to look him straight in the eye, and I want
to tell him what a cheap, lying, no-good, rotten, four-flushing, low-life,
snake-licking, dirt-eating, inbred, overstuffed, ignorant, blood-sucking,
dog-kissing, brainless, dickless, hopeless, heartless, fat-assed, bug-eyed,
stiff-legged, spotty-lipped, worm-headed, sack of monkey shit he is!
Hallelujah! Holy shit! Where's the Tylenol?"

---

This captures the full intensity and humor of Clark's frustration in that
memorable scene.

Citations:
[1] National Lampoon's Christmas Vacation1989
https://www.quotes.net/mquote/122538

**Comment by linlinxza** [comment]
> Hi I swear I'm not just feeling extra agreeable today but I usually agree YouTube does not count as social media My well my unified theory will actually show that many of Terence McKenna's statements were more than just metaphors probably

It's all social media really. If it has a comments section, it's social media. And it's designed to be just as addictive as any other social media platform. Least I can say Odysee and Peertube aren't really social as hardly anyone comments on videos there. Which is nice.

**Comment by crowlogic** [comment]
Holy smokes is the email social media? I feel so dirty I need to take a
shower

**Comment by linlinxza** [comment]
> Holy smokes is the email social media? I feel so dirty I need to take a shower

Nope. It isn't like everyone can see a regular email like you could see everyone's comments on YouTube. Anyway, nice chatting.

PS: I haven't been talking on here through email. Just FYI.

**Comment by crowlogic** [comment]
You too homie, best internet chat I've had that I can remember in quite
some time.

**Comment by mkiol** [comment]
Closing because initial the problem has been resolved :)
