### ISSUE TITLE
Crash under fedora 40

### ISSUE THREAD

**Issue by tkalfaoglu** [mkiol/dsnote#172]
I installed the program under fedora using Flatpak,and the AMD plugin  (flatpak asked user or system, I picked system).  It started out fine, I added a few languages, now it won't start (even with hardware off). I get these and then it closes its main window.

$ flatpak run net.mkiol.SpeechNote  --hw-scan-off --verbose
[D] 13:23:42.897079510.897 0x7f43cd600680 libs_availability:211 - checking: unidic-lite
[D] 13:23:42.897676724.897 0x7f43cd600680 libs_availability:218 - py libs availability: [coqui-tts=true, faster-whisper=true, mimic3-tts=true, whisperspeech-tts=true, transformers=true, unikud=true, gruut_de=true, gruut_es=true, gruut_fa=true, gruut_fr=true, gruut_nl=true, gruut_it=true, gruut_ru=true, gruut_sw=true, mecab=true, torch-cuda=false, torch-hip=true]
[D] 13:23:43.486562180.486 0x7f43ee1d5d00 () - trying features availability update: true
[D] 13:23:43.486648792.486 0x7f43ee1d5d00 () - features availability ready
[W] 13:23:43.487184170.487 0x7f43ee1d5d00 has_lib:877 - failed to open libcudart.so: libcudart.so: cannot open shared object file: No such file or directory
[W] 13:23:43.487334723.487 0x7f43ee1d5d00 has_lib:877 - failed to open libcudnn.so: libcudnn.so: cannot open shared object file: No such file or directory
[W] 13:23:43.487460760.487 0x7f43ee1d5d00 has_lib:877 - failed to open libcudnn.so.8: libcudnn.so.8: cannot open shared object file: No such file or directory
[W] 13:23:43.560614496.560 0x7f43ee1d5d00 has_cuda:60 - failed to open whisper-cublas lib: libwhisper-cublas.so: cannot open shared object file: No such file or directory
[W] 13:23:43.560770099.560 0x7f43ee1d5d00 has_cuda:60 - failed to open whisper-cublas lib: libwhisper-cublas.so: cannot open shared object file: No such file or directory
[D] 13:23:43.731309863.731 0x7f43ee1d5d00 () - updating models using availability: tts_coqui, tts_mimic3, tts_mimic3_de, tts_mimic3_es, tts_mimic3_fr, tts_mimic3_it, tts_mimic3_ru, tts_mimic3_sw, tts_mimic3_fa, tts_mimic3_nl, tts_rhvoice, tts_whisperspeech, stt_fasterwhisper, stt_ds, stt_vosk, mnt_bergamot, ttt_hftc option_r,
[D] 13:23:43.731360258.731 0x7f43ee1d5d00 () - updating model using availability internal
[D] 13:23:43.734100864.734 0x7f43ee1d5d00 () - default tts model not found: "en"
[D] 13:23:43.734118247.734 0x7f43ee1d5d00 () - default mnt lang not found: "en"
[D] 13:23:43.734123046.734 0x7f43ee1d5d00 () - new default mnt lang: "en"
[D] 13:23:43.734175465.734 0x7f43ee1d5d00 () - service refresh status, new state: idle
[D] 13:23:43.734182247.734 0x7f43ee1d5d00 () - service state changed: busy => idle
[D] 13:23:43.734221361.734 0x7f43ee1d5d00 () - scan cuda: false
[D] 13:23:43.734227102.734 0x7f43ee1d5d00 () - scan hip: false
[D] 13:23:43.734231530.734 0x7f43ee1d5d00 () - scan openvino: true
[D] 13:23:43.734236660.734 0x7f43ee1d5d00 () - scan openvino_gpu: false
[D] 13:23:43.734241870.734 0x7f43ee1d5d00 () - scan opencl: false
[D] 13:23:43.734246348.734 0x7f43ee1d5d00 () - scan opencl legacy: false
[D] 13:23:43.734251989.734 0x7f43ee1d5d00 () - hw feature flags: stt-whispercpp-hip, stt-whispercpp-openvino, stt-whispercpp-opencl, tts-coqui-hip tts-whisperspeech-hip
[D] 13:23:43.734257529.734 0x7f43ee1d5d00 add_openvino_devices:813 - scanning for openvino devices
[D] 13:23:43.735537818.735 0x7f43ee1d5d00 add_openvino_devices:825 - openvino version: build=2024.1.0-15008-f4afc983258-releases/2024/1, description=OpenVINO Runtime

**Comment by tkalfaoglu** [comment]
[lshw.txt](https://github.com/user-attachments/files/17476911/lshw.txt)

**Comment by mkiol** [comment]
Hi. Thanks for reporting.

It looks that OpenVINO is causing the crash. Option ` --hw-scan-off` should disable it, but due to a bug it did not work. Could you please manually edit configuration file and add or edit following entry under `[General]` section:

~/.var/app/net.mkiol.SpeechNote/config/net.mkiol/dsnote/settings.conf

```
hw_scan_openvino=false
```

**Comment by mkiol** [comment]
Hi. I've released Beta version which works much better with AMD graphics card.

More details how to install Beta can be found [here](https://github.com/mkiol/dsnote/issues/179).

The most important change is GPU acceleration support with Vulkan on WisperCpp models. It is ultra fast and you don't need to install any Add-ons to use it.

**Comment by mkiol** [comment]
The new version 4.7.0 is out and available on flathub. 

The new version includes many fixes and Vulkan GPU acceleration, which is the recommended configuration for AMD graphics cards.

If the problem persists with v4.7.0, please reopen.
