### ISSUE TITLE
Speech to text output always English

### ISSUE THREAD

**Issue by ghost** [mkiol/dsnote#176]
Hello, I have installed Speech Note on a rather old notebook and it works really well.
There's only one small issue: I can speak in German or English and it will always output English. All this although I only have a German language package installed, namely, FasterWhisper Small in German. 
I use Speech Note on Ubuntu 24.04 and my default system language is English.

**Comment by mkiol** [comment]
Hi. Thanks for the report.

Most likely you have automatic English translation enabled. There is a "switch" between name of the model and "Listen" button. It should be turned off.

![image](https://github.com/user-attachments/assets/dabf9094-26b7-4bf1-84ba-d71dd77a651b)

**Comment by mkiol** [comment]
I assume that the problem has been solved. If not, please reopen.
