### ISSUE TITLE
Slovenian menu for speechNote

### ISSUE THREAD

**Issue by matjazjeran** [mkiol/dsnote#177]
I made Slovenian translation for speechNode included here. If you find it good enough, you are welcome to distribute it.
[dsnote-sl.zip](https://github.com/user-attachments/files/17666433/dsnote-sl.zip)

I find the program quite useful for Slovenian although it is not as polished as for English yet.
Thanks to all developers!

**Comment by mkiol** [comment]
That is super cool :) Thank you for your contribution.

Commit: 0f00fc152d27538e263f6a8635d990e139e6ed2f 

Your translation is also available via transifex service: https://app.transifex.com/mkiol/dsnote/language/sl/
