### ISSUE TITLE
Request to add whisper turbo models

### ISSUE THREAD

**Issue by iamashwin99** [mkiol/dsnote#178]
Hi
Is it possible to add turbo whisper models like `deepdml/faster-whisper-large-v3-turbo-ct2` ?
I saw that they are actually very fast when running them manually on my device and would be nice to have them in the dsnote GUI as well.

**Comment by mkiol** [comment]
Hi. Thanks for the request.

It is already added in 1d971941e2c2019027b12513e6f9c2d0a31140b0, but not yet released in official version.

You can test Turbo models (and other improvements) by installing Beta version. 

More details can be found [here](https://github.com/mkiol/dsnote/issues/179).

**Comment by mkiol** [comment]
The new version 4.7.0 is out and available on flathub. 

The new version includes:

- New _Whisper Large Turbo_ model for both _WhisperCpp_ and _FasterWhisper_.

Video presentation of all the new features introduced in version 4.7.0: https://www.youtube.com/watch?v=cEht4Fts6Bo
