### ISSUE TITLE
issue when load flatpak 

### ISSUE THREAD

**Issue by bedlex** [mkiol/dsnote#180]
flatpak run net.mkiol.SpeechNote 
Gtk-Message: 19:24:01.677: Failed to load module "xapp-gtk3-module"
Gtk-Message: 19:24:01.694: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:24:01.695: Failed to load module "canberra-gtk-module"
qt.qpa.qgnomeplatform: Could not find color scheme  ""

**Comment by mkiol** [comment]
Hi. Thanks for the report.

To see more logs, could you please start the app with `--verbose` option:

```
flatpak run net.mkiol.SpeechNote --verbose
```

**Comment by bedlex** [comment]
Found solution. Just edit the configuration file 
~/.var/app/net.mkiol.SpeechNote/config/net.mkiol/dsnote/settings.conf
[General]
***
use_tray=true

just replaced use_tray=false and program starts

Guess need to add some function that check if OS supports tray.

**Comment by mkiol** [comment]
I'm glad you found a solution! Still, if it's not a problem, can you paste the output when the app fails to start? It will help me to implement the fix.

```
flatpak run net.mkiol.SpeechNote --verbose
```
