### ISSUE TITLE
Graphic card stuck after a while when GPU acceleration is on

### ISSUE THREAD

**Issue by mlo-3** [mkiol/dsnote#184]
Hi, thanks for the app. It is awesome.

I have a new freeze behavior (used to work without freeze) : the graphic card no longer render screen and show a green or black color screen, and stay stuck like this. Part of the computer is still running (playing music does not stop).
It seems to happens when I talk for more than 15sec (around) without pause. I have to reboot the computer. 

It does not seems to be an overload of the card, since I tested it with GPU-burn with no freeze.
 
Any hints ?

Spec : 
Manjaro Linux up to date
NVIDIA GeForce GTX 1050 Ti
NVIDIA-SMI 550.120 
Driver Version: 550.120 
CUDA Version: 12.4     
"Flash attention" option is off, audio context is "Dynamic"

**Comment by mkiol** [comment]
Hi. Thanks for reporting.

Do you use Flatpak or AUR version?

Would you be able to start with `--verbose` option?

```
flatpak run net.mkiol.SpeechNote --verbose
```

or in case AUR:

```
dsnote --verbose
```

**Comment by mlo-3** [comment]
Thanks. I currently use flatpak.

Here is the output of a session without card freeze, if it says something useful : 
https://pastebin.com/7qbknfAm

If I go to a freeze I will loose the terminal output.

**Comment by mkiol** [comment]
Thanks for the logs. I don't know what could be causing the observed problem, but...

You are using WhisperCpp with OpenCL acceleration which is sub-optimal. Did you try to install NVIDIA add-on (`flatpak install net.mkiol.SpeechNote.Addon.nvidia`) and enable CUDA acceleration for WhisperCpp? Your GPU supports CUDA and you will get better performance on CUDA instead of OpenCL.

Alternatively, you could try to install [4.7.0-beta](https://github.com/mkiol/dsnote/issues/179) release. In beta you can enable Vulkan acceleration that gives excellence performance without installing any GPU add-on.

**Comment by mlo-3** [comment]
I thought Cuda was already working. Just installed it (cudnn…) and it now works faster indeed !
Many thanks !

I also tried to speak more than 15 sec, to make the bug happen, and it did not happen. Maybe this fixed it, using CUDA instead of openCL. 

I'll come back here if it happens again.

**Comment by mlo-3** [comment]
Well, it crashed again. Since it was not in previous version, I hope next version will incidentally correct the problem.
Are there a log somewhere to document the event of the graphic card freeze ? (which occurs only when using Speech Note)

**Comment by mkiol** [comment]
> I hope next version will incidentally correct the problem.

I encourage you to try [4.7.0-beta](https://github.com/mkiol/dsnote/issues/179) and enable Vulkan acceleration for WhisperCpp.

> Are there a log somewhere to document the event of the graphic card freeze?
> If I go to a freeze I will loose the terminal output.

I forgot that there is a `--log-file` option. You could try to start Speech Note and write the logs to a file. Maybe this is a solution for "loosing terminal output"?

```
flatpak run net.mkiol.SpeechNote --verbose --log-file dsnote_log.txt
```

**Comment by mlo-3** [comment]
Hi, 

4.7.0-beta and Vulkan seems to have fixed the problem.

Thank you !

**Comment by mkiol** [comment]
I am glad to hear that! Since the problem has been solved, I am closing the issue.

**Comment by mlo-3** [comment]
Hello, happened again twice this morning, was running fine yesterday though nothing changed (except the temperature of graphic card and motherboard). I'll try to go through the logs and report it. 
Edit : it happened with another software too (mpv). First time.
