### ISSUE TITLE
Add action to read the application status

### ISSUE THREAD

**Issue by yannxaver** [mkiol/dsnote#186]
This is related to my previous issue #185 

`flatpak run net.mkiol.SpeechNote --help-all`

```
--action <action>                    Invokes an <action>. Supported actions
                                       are: start-listening,
                                       start-listening-active-window,
                                       start-listening-clipboard,
                                       stop-listening, start-reading,
                                       start-reading-clipboard,
                                       pause-resume-reading, cancel,
                                       switch-to-next-stt-model,
                                       switch-to-prev-stt-model,
                                       switch-to-next-tts-model,
                                       switch-to-prev-tts-model, set-stt-model,
                                       set-tts-model.
```

If you added another action that returned the current status of the application (e.g. `listening`, `transcribing`, `idle`, etc.) it would bring several benefits:

1. One global hotkey would be sufficient to start / stop the dictation because the current status of the application could be known.
2. Custom status bar widgets could be created that integrate with `dsnote` and display the status of the application

**Comment by mkiol** [comment]
Thanks for this idea. It can indeed be useful. I will try to implement it in the next version.

**Comment by mkiol** [comment]
The new version 4.7.0 is out and available on flathub. 

The new version includes new command line options:

- `--print-available-models`
- `--print-active-model`
- `--print-state`
