### ISSUE TITLE
Can't find GPU acceleration add on

### ISSUE THREAD

**Issue by paul1149** [mkiol/dsnote#190]
Hello,

I installed Speech Note 4.6.1 via the MX Linux Package Installer's Flatpak tab. Initially it offered three candidates, one for nvidia gpu, one for AMD gpu, and the base one, SpeechNote. I chose the base, because at 3GB it was large enough. The others were clocking some 16GB, as I recall.

It's working very well, but it is fairly slow. The interface tells me the GPU accel is not installed and encourages me to install it. But now when I go back to the MXPI's Flatpak tab, the GPU add-ons are nowhere to be found.

If I go directly to Flathub.org it tells me to install the add-ons via my distro. So I'm stuck.

Is there a way to install the AMD add-on, and would it really be some 16GB? Would uninstalling the base product make the GPU-based offerings appear again? This is by far the best speech to text experience I've seen on Linux.

Thanks.

**Comment by mkiol** [comment]
Hi. Thanks for the question.

If you package installer app does not let you find Flatpak add-on, you can install it using terminal.

To search all Speech Note packages:

```
$ flatpak search SpeechNote

Name                          Description                                                                          Application ID                              Version           Branch           Remotes
Speech Note NVIDIA            Support for GPU acceleration with NVIDIA graphics cards in Speech Note               net.mkiol.SpeechNote.Addon.nvidia           1.2.1             stable           flathub
Speech Note AMD               Support for GPU acceleration with AMD graphics cards in Speech Note                  net.mkiol.SpeechNote.Addon.amd              1.2.1             stable           flathub
Speech Note                   Notes with offline Speech to Text, Text to Speech and Machine Translation            net.mkiol.SpeechNote                        4.6.1             stable           flathub
Speech Note NVIDIA            Support for GPU acceleration with NVIDIA graphics cards in Speech Note               net.mkiol.SpeechNote.Addon.nvidia           1.3.0             beta             flathub-beta
Speech Note AMD               Support for GPU acceleration with AMD graphics cards in Speech Note                  net.mkiol.SpeechNote.Addon.amd              1.3.0             beta             flathub-beta
Speech Note                   Notes with offline Speech to Text, Text to Speech and Machine Translation            net.mkiol.SpeechNote                        4.7.0             beta             flathub-beta
```

To install add-on package for AMD:

```
flatpak install net.mkiol.SpeechNote.Addon.amd
```

If you have an AMD graphics card, I strongly recommend trying "pre-release" [4.7.0 Beta](https://github.com/mkiol/dsnote/issues/179) version. It comes with support for Vulkan GPU acceleration for WhisperCpp STT models. It's super fast and doesn't require this huge AMD add-on. You can use it having the "basic" package installed.

**Comment by paul1149** [comment]
Thanks very much for that thorough answer. I've installed the beta, and it is indeed quite fast. Also, the SRT function is very cool.

I think the beta required a full 3.2GB download, which is what the basic package had weighed in as. But it is worth it for the increased speed.

Thanks very much. I look forward to working with this. This really shores up an area where Linux was lacking.

**Comment by paul1149** [comment]
Also, I've discovered that setting the Listening Mode to Always On makes a huge improvement in usability.

**Comment by SugarRayLua** [comment]
@mkiol,
For us Ubuntu AMD users, does the 4.7.1 release contain GPU acceleration functionality or shoulde we stick still with the 4.70 Beta for that functionality still for now.
Thanks!

**Comment by mkiol** [comment]
@SugarRayLua 
If you are looking for fast and accurate speech-to-text, you can use WhisperCpp models with Vulkan acceleration. To use Vulkan, you don't need to install any additional packages - just install the latest `net.mkiol.SpeechNote` package from Flathub (which is version 4.7.1 right now).

The upcoming [4.8.0 beta](https://github.com/mkiol/dsnote/issues/223) version is also available, but on the Fluthub Beta channel. This version includes new and powerful text-to-speech models such as Kokoro, Parler-TTS and F5-TTS. These models are very slow on the CPU. Practically, to use them on AMD GPUs, you must also install the "add-on" package `net.mkiol.SpeechNote.Addon.amd`.

Note that the `net.mkiol.SpeechNote.Addon.amd` package has a very large size. You need 25 GiB! This is a reason I don't recommend to install it.

Here are more details about what the add-on package gives you: https://github.com/mkiol/dsnote?tab=readme-ov-file#flatpak-packages

**Comment by SugarRayLua** [comment]
Perfect, @mkiol, thanks-- I'll try your suggestions! :-)
