### ISSUE TITLE
Support GNOME Wayland for dsnote

### ISSUE THREAD

**Issue by Francewhoa** [mkiol/dsnote#20]
## Summary

The challenge is that as of August 23, 2023, dsnote does not support GNOME Wayland. This is a challenge because, by default, [most of the recent versions of Linux distributions (distros) now use GNOME Wayland](https://en.wikipedia.org/wiki/Wayland_(protocol)#Desktop_Linux_distributions) by default. Not GNOME X11. Linux's distributions, such as, but not limited to, Debian, Fedora, Manjaro, Red Hat Enterprise Linux, Ubuntu, etc.

The suggested resolution is to configure your Flatpak package appropriately so that it supports Wayland. The end result is that both GNOME Wayland and X11 are supported. If you're interested in this, this documentation about [Flatpak sandbox](https://github.com/flatpak/flatpak/wiki/Sandbox#host-changes-needed) might be useful. If somehow this documentation is not available, this [archived page](https://archive.md/149tR#host-changes-needed) might be of interest. Alternatively, [Flatpak support for maintainers is available here](https://github.com/flatpak/flatpak/issues?q=is%3Aissue+wayland).

Below is the same as above. But with details if you're interested in those.

## Steps to reproduce

1. Using Linux Debian 10 (Buster) 64 bits, using GNOME 3.30.2, using GNOME with its option Wayland, using the steps from https://flathub.org install the Flatpak for dsnote 4.1.0
1. dsnote will fail to start, and will not open. In other words, it is not usable. This is the challenge. When starting dsnote from Terminal/Console, this error message is display:
```/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=dsnote net.mkiol.SpeechNote
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
qt.qpa.qgnomeplatform: Could not find color scheme  ""
Complété
```
3. The needed end result is that dsnote is able to start with GNOME Wayland.
1. Close the present GNOME Wayland session
1. Using the GNOME user log-in front page, click on the cogwheel button on the right side of the log-in field. Using this button drop down menu, temporarily change the GNOME option from Wayland to the unsecured X11.
1. Using GNOME X11, start dsnote
1. It will open successfully. I don't know why dsnote does open in X11 but not in Wayland. My guess is that, somehow, dsnote does not yet support GNOME Wayland.
1. Log out GNOME. If appropriate, switch back to Wayland. 

## Flatpak page

https://flathub.org/fr/apps/net.mkiol.SpeechNote

## Contribute

If needed, both me and the Ubertus.org team would be happy to contribute beta testing and documentation for this improvement or new feature. Any volunteer for a patch?

**Comment by mkiol** [comment]
Thank you for reporting. 

To be honest, I have never tested on Wayland. I will look into it.

**Comment by Greenheart** [comment]
I'm successfully using `dsnote` on Fedora 38 with GNOME 44.4.

By running the `xprop` command as described by https://superuser.com/a/1792349, I was able to determine that `dsnote` is indeed running as a Wayland app.

There are some minor issues with dark mode (text not adapting to work when GNOME has dark mode enabled), but there is nothing critical that prevents me from using this app on Wayland.

1. In the settings, "Font size in text editor" should ideally be white when system dark mode is enabled. 
![Screenshot from 2023-08-29 12-41-45](https://github.com/mkiol/dsnote/assets/6125097/20b383cd-2e15-42c4-9036-c0ec11e78a47)

2. The text "Translator model has not been setup yet (...)" should ideally be white when system dark mode is enabled.
![Screenshot from 2023-08-29 12-42-52](https://github.com/mkiol/dsnote/assets/6125097/65912405-c7db-40c5-9af2-b55b0f3e5477)

I'll let you know if I find anything more when using this on Wayland - keep up the good work! :)

**Comment by mkiol** [comment]
@Greenheart Thank you for confimation that it works in Wayland as well.

Regarding "ugliness" under GNOME with dark theme. I have to say it is still a mystery to me why some parts of the UI respect darkness and some do not (???). Good news is I've managed to find better workaround for this problem. Stay tuned for the next release 😃.

**Comment by Greenheart** [comment]
Sounds exciting! Thank you - and make a great day! 🌳

**Comment by Greenheart** [comment]
Oh, also the notification that appears in the center of the screen after an audio file export is completed is showing up as white text on a white background.

**Comment by mkiol** [comment]
New release 4.2.0 is available on Flathub.

Glitches under dark theme should be fixed.. but still app looks rather ugly under GNOME. 

In this version there is new option 'Graphical Style' which lists all Qt component styles installed in the OS. The default is 'org.kde.desktop' (not 'Default'). I tested all styles on Ubuntu 22.04 with GNOME and it appears that style 'org.kde.breeze' looks the best. Not perfect but decently.

**Comment by Greenheart** [comment]
Thank you! The `org.kde.breeze` theme looks best indeed.

**Comment by mkiol** [comment]
The app seems to work fine under Wayland, so closing the issue.
