### ISSUE TITLE
Donate button

### ISSUE THREAD

**Issue by harkai84** [mkiol/dsnote#21]
Hello,

the new version of your program is really nice. Is it possible to spend you money for your hard work?
I look into the github page but i dont see any button.
:)

**Comment by mkiol** [comment]
Thank you. It is a very nice feeling to know that my work is useful 😃.

Right now I don't accept donations. Maybe in the future... 

This app is possible thanks to many amazing open source projects. The list  is at the bottom of [README](https://github.com/mkiol/dsnote/blob/main/README.md#libraries) file. You might consider donating one of them (I did check if they actually accept any donations).
