### ISSUE TITLE
Command line arguments for automation

### ISSUE THREAD

**Issue by sandorex** [mkiol/dsnote#24]
I would love it if there was a way to create audio files via commandline for a bit more automation

**Comment by mkiol** [comment]
I've been thinking about this for a while and I'm not super convinced that this app is a right tool to do automation.

I strongly recommend you to checking the projects which Speech Note uses. 

For TTS it will be:

- [Coqui TTS](https://github.com/coqui-ai/TTS) - A python library and also command-line program (`tts`). It has many more options to control TTS. Perfect tool for automation. Great quality of speech synthesis.
- [Piper](https://github.com/rhasspy/piper) - Command-line program. Perfect tool if you looking for something that is super fast and doesn't need many resources.

**Comment by sandorex** [comment]
Thanks for recommendation, but i thought maybe pretty basic argument forwarding to the application speech note uses
The app is still quite useful for downloading models :smile:

**Comment by mkiol** [comment]
Fair enough 👍🏿 I will try to add something basic. Probably not in upcoming release and next one.
