### ISSUE TITLE
[TTS] Add Mimic 3 models

### ISSUE THREAD

**Issue by JamesClarke7283** [mkiol/dsnote#25]
I would like to see the Mimic 3 models in this app

A link to the GitHub is [HERE](https://github.com/MycroftAI/mimic3).

It does a better job than Piper in my opinion and sounds more real.

P.S Awesome Project, keep up the good work.

**Comment by mkiol** [comment]
I will look in to it. 

BTW, I always thought that Piper is a successor of Mimic3 and eventually will replace it. Maybe I'm wrong. Both engines seems to be developed by the same people 🤔

**Comment by JamesClarke7283** [comment]
> I will look in to it.
> 
> BTW, I always thought that Piper is a successor of Mimic3 and eventually will replace it. Maybe I'm wrong. Both engines seems to be developed by the same people 🤔

They are made by different people.

Piper is made by the rhasspy people:
https://github.com/rhasspy/piper

Mimic is made by the Mycroft people:
https://mycroft.ai/mimic-3/

In my opinion the Mimic 3 voices sound better than Piper. but that's just my opinion.

You can find a demo on my instance here:
https://voice.james-clarke.ynh.fr/

**Comment by mkiol** [comment]
Implemented in 203d13ae02f6b3c06dd6cb7a91b125ad21d2d2c8.

This change is included in "beta" version. You can install and test "beta" version from [`flathub-beta`](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) channel.
