### ISSUE TITLE
Not an issue. I am just very impressed with the quality of certain voices.

### ISSUE THREAD

**Issue by linlinxza** [mkiol/dsnote#27]
I am impressed with the Piper Ryan high and Piper Lessac high version is very human sounding. And I am impressed that this little program makes all the voices easily accessible.

**Comment by mkiol** [comment]
You're welcome 😃. I'm very glad you find this program useful.

To be perfectly honest, all kudos should go to amazing [Piper](https://github.com/rhasspy/piper) team. They provided models and the engine responsible for speech synthesis. I just gathered all the pieces together and packaged them with a GUI.

**Comment by linlinxza** [comment]
> You're welcome 😃. I'm very glad you find this program useful.
> 
> To be perfectly honest, all kudos should go to amazing [Piper](https://github.com/rhasspy/piper) team. They provided models and the engine responsible for speech synthesis. I just gathered all the pieces together and packaged them with a GUI.

But it would be great if you could add a feature to add pronunciation for certain words. Of course, I just use sed in a script to replace the words with the correct pronunciation and then just have it sent to the clipboard for pasting into Speech Note.
