### ISSUE TITLE
service isn't restarted after switching storage directory

### ISSUE THREAD

**Issue by DrYak** [mkiol/dsnote#3]
In Speech Notes' settings, when changing the directory where the Deep Speech models are stored, the _harbour-dsnote.service_ isn't restarted and keep looking at the old (wrong) path.

Context:
- I've been using Speech Notes on my Xperia XA2 (32GB edition, not that much storage available for `/home`)
- I'm storing the models on the external SD card
- I've recently switch to an Xperia 10iii, and installed Speech Notes on it too
- I've moved the SD card to the new device
- I've changed the _Location of language files_ to point to the path on the SD Card.
- Speech Notes now sees the already installed language models.
- Speech Notes can even download new models.
- BUT the settings doesn't allow me to select a model, only to download new
- and the main pannel complains that no model has been configured.

Current work-around:
- as the user (E.g.: nemo or defaultUser)
```shell
systemctl --user restart harbour-dsnote.service
```

Request:
- Could it be possible for the app to trigger the service restart?
- Or could you change the API so clients such as Speech Notes could send a "_please restart_" command?

**Comment by mkiol** [comment]
Thank you for the detailed explanation. Most likely it is a bug. Service `harbour-dsnote.service` should restart itself automatically after directory change.

I will look into it and resolve the problem in the upcoming release.

**Comment by mkiol** [comment]
Resolved in 2de7c2aac3af2bfed6a4c472ff4073f7a70ab4d7. The fix is included in 2.0.0 release.
