### ISSUE TITLE
Hotkeys would be nice :)

### ISSUE THREAD

**Issue by harkai84** [mkiol/dsnote#40]
hello,

enter for reading
p for pause
and more if you like.
Maybe you can add some things in the settings to config all hotkeys.
:)

**Comment by mkiol** [comment]
Good news. It is already implemented as `Global keyboard shortcuts` in `Settings`->`Accessibility`. Not yet released but you can test it by installing Speech Note from flatpak-beta. 

If you not familiar with flatpak-beta, [here](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) is short how-to.

Worth mentioning, shortcuts work **only on X11**. If you are on Wayland, you might try to use "actions" to trigger certain operation (start-listening, start-reading, pause itd..). An action can be invoked via command-line or with DBus call, so you can integrate it into your desktop.

**Comment by mkiol** [comment]
I'd like to know what you think about this feature. If anything needs to be added or changed, please let me know.

**Comment by mkiol** [comment]
Closing because this feature is already included in "beta" release. You can install and test "beta" version from [`flathub-beta`](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) channel.

**Comment by black-puppydog** [comment]
I'm not sure where to find this actually I see in this was code that somehow there are some conditions for using those global shortcuts But I don't really know how to activate them and they don't seem to show up for me neither in the regular version nor in the beta version.

Is there something obvious I'm missing?

**Comment by mkiol** [comment]
@black-puppydog 
Thanks for asking. I suspect you are running Wayland session and "Global shortcuts" is only available under X11 right now.

**Comment by black-puppydog** [comment]
You were right, thanks!
