### ISSUE TITLE
Support for aprilasr

### ISSUE THREAD

**Issue by road2react** [mkiol/dsnote#44]
Hello,

I really appreciate your project! I think it's going in a very nice and useful direction!

[LiveCaptions](https://github.com/abb128/LiveCaptions) uses [aprilasr](https://github.com/abb128/april-asr), which is very fast and only needs the CPU. 

I think it would be great if you could add aprilasr as one of the speech recognition options in your project. 

It would add a lot of value to your project by offering a fast and lightweight option for user's who don't have access to GPUs or want to conserve battery life on mobile devices.

Thanks in advance! Good luck with the rest of the project ;)

**Comment by mkiol** [comment]
Written in C, quite fast and has this nice capability of returning intermediate/partial results. It looks very interesting I must say.

**Comment by mkiol** [comment]
Implemented in 8c6f48db17869c2636aec537be216dbf359817ec.

This change is included in "beta" release. You can install and test "beta" version from [`flathub-beta`](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) channel.
