### ISSUE TITLE
Missing support for certain file formats

### ISSUE THREAD

**Issue by road2react** [mkiol/dsnote#45]
In the latest version, it is not possible to select video files to transcribe the audio. Additionally, these formats are not supported:

- ogg opus (gets stuck at 100%, no transcribed text in output) [example file](https://cdn.discordapp.com/attachments/1143770886965575681/1162943941692375170/voice_recording.ogg?ex=653dc6f2&is=652b51f2&hm=e5073af85b3d55272e575379e0b100d42fb7c8820a6d8293c455308926e6cd3d&)
- mp3

**Comment by mkiol** [comment]
Thanks for the report.

- Opus is not supported and there is a bug in handling of "unsupported codec" situation. Working on a fix.
- MP3 should work fine. If not, could you please provide me example file? It would be very helpful.
- Transcribing video files should work as well if audio codec is supported. Following codecs are enabled right now: aac, mp3, flac, vorbis.

**Comment by mkiol** [comment]
79f788fb7efeb70a2e6a7b34f3fb37f65e1baad5
4627f7674a6f71d7533c4c927dbe41f99f4dee8c

**Comment by road2react** [comment]
> Transcribing video files should work as well if audio codec is supported. 

Previous versions worked for video files, but they no longer show up in the file select dialog in latest version.

**Comment by mkiol** [comment]
Could you please check the latest "beta" release?

You can install and test "beta" version from [`flathub-beta`](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) channel.

**Comment by mkiol** [comment]
I think it is fixed in latest 4.3.0 version. If not, please re-open.
