### ISSUE TITLE
Add open dyslexic font

### ISSUE THREAD

**Issue by albanobattistella** [mkiol/dsnote#46]
Hi,
It might be very useful to add open dyslexic fonts for some people who need it.
Also, import PDF files for transformation into audio files.
Thanks.
A.

**Comment by mkiol** [comment]
Noted :)

**Comment by mkiol** [comment]
Just letting you know if you want to test it before the release. Version 4.5.0-beta (on [`flathub-beta`](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111)) has `Font in text editor` settings option. You can set any font you want.

![image](https://github.com/mkiol/dsnote/assets/1420902/698ec2f0-33f0-43bc-ab46-8b86828ac70f)

**Comment by albanobattistella** [comment]
Thanks! :-)

**Comment by mkiol** [comment]
New release 4.5.0 brings the following:

- Enhanced text editor font settings. You can set the font family, style and size of the font used in the text editor.
