### ISSUE TITLE
'--action' and dbus issue

### ISSUE THREAD

**Issue by BorisCarvajal** [mkiol/dsnote#50]
Thanks for this app!

I found the following issues while exploring the automation tools provided via the beta flatpak.

First, invoking any of the reading actions (`start-reading`, `start-reading-clipboard`, or `pause-resume-reading`) through `--action` cmdline option will not work, the program just prints:

  `Invalid action. Use one option from the following: start-listening, start-listening-active-window, start-listening-clipboard, stop-listening, start-reading, start-reading-clipboard, pause-resume-reading, cancel.`

Second, I didn't have any problem using the dbus `org.freedesktop.Application` interface, calling `ActivateAction` works perfectly fine. But I could not find what is defined in `dbus/org.mkiol.Speech.xml` on the dbus session, it seems that powerful interface isn't exposed at all. Is this normal?

**Comment by mkiol** [comment]
Thanks for catching this!

Fixed in d8b3772e0c1341e31e4b1babc9408626de5e2c64. I will push new "beta" today.

> But I could not find what is defined in dbus/org.mkiol.Speech.xml on the dbus session, it seems that powerful interface isn't exposed at all. Is this normal?

This interface works only in so called "split mode". You can start the program with `--service` or `--app` option. The Service is a UI-less process that can be run as a daemon. The App communicate with the service via `org.mkiol.Speech` DBus API. I use this mode only on SaifishOS where Speech Note service  is used also as a back-end for speech-to-text keyboard. On a desktop I didn't find any use for this. Besides, this API is certainly blocked by Flatpak sandbox right now.

**Comment by nerumo** [comment]
Interesting. I'm looking for something that can be integrated more deeply into desktops. Something in the OS that hovers over the current cursor which can activate speech input and directly insert the content.

Here's a screenshot how it's implemented in Windows:
![image](https://github.com/mkiol/dsnote/assets/8597645/42f1e0aa-b643-4223-801e-c06fe3f6a487)

How did you use it in Sailfish OS?

**Comment by mkiol** [comment]
Actually, something similar was requested in https://github.com/mkiol/dsnote/issues/33.

Right now, this "accessibility" feature works only under X11. You can use keyboard shortcut or command line option to trigger "listening". Once the voice is converted to text, it is inserted to any text box cursor is in. 

To make this happen, the application sends a combination of keypress events. These key events are interpreted by the X11 server as actual keystrokes, so you can push the text to an external app/window. Quite "hacky" but works well.

You can test this feature in beta version (from `flathub-beta` repo).

**Comment by mkiol** [comment]
> How did you use it in Sailfish OS?

Keyboard shortcut or "actions" are used only on Linux Desktop version of Speech Note. On Sailfish OS, Speech Note is integrated with native phone virtual keyboard. On virtual keyboard you have a button to insert text with voice.

**Comment by nerumo** [comment]
thanks for the hint, awesome. unfortunatly I'm using wayland. Since the input handling is done by the compositor (kwin, mutter, wlroot) , I assume that there's no common api to do this... except dbus perhaps?

**Comment by mkiol** [comment]
> Since the input handling is done by the compositor (kwin, mutter, wlroot) , I assume that there's no common api to do this... except dbus perhaps?

X11 server accepting any key-events from any application is problematic actually. This is considered an X11 security vulnerability and this type of functionality is intentionally missing in Wayland. 

I must admit that I have not yet checked whether there is a replacement API in Wayland that could be used to implement something similar. I suspect not, but I could be wrong.

**Comment by mkiol** [comment]
@BorisCarvajal Fix is included in the recent 4.3.0 release.
