### ISSUE TITLE
Drag and drop support

### ISSUE THREAD

**Issue by user91756** [mkiol/dsnote#51]
Is drag and drop support for .mp3 files a possibility?  Having to choose File:Transcribe a file:selecting a directory and changing from audio to all files for .mp3 to show up is tedious.  A bonus would be for the name of the audio file to auto populate the text save dialog box.  Maybe it could be fixed with Flatseal but I am not sure how.

Side note:
Using the whisper model gives great results.  I can confirm that enabling GPU support in the settings does work as I see the GPU memory and usage spike when the transcription is occurring using Mint 21.2 and an Nvidia RTX 3050.
Would love to make a monetary contribution but I am unable to find a link unless I overlooked it.

**Comment by mkiol** [comment]
Thanks for the report.

> Is drag and drop support for .mp3 files a possibility?

Actually, it is already implemented. Will be in upcoming release. You can test "beta" version by installing Speech Note from [`flathub-beta`](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) channel. Warning: Beta might have many bugs.

> A bonus would be for the name of the audio file to auto populate the text save dialog box

👍🏿 

> Using the whisper model gives great results. I can confirm that enabling GPU support in the settings does work

Thanks for the confirmation. I'm super happy it works well.

> Would love to make a monetary contribution

That's nice of you :) Currently I do not accept donations.. maybe in a future.

**Comment by mkiol** [comment]
"Drag and Drop" feature is included in the recent 4.3.0 release.
