### ISSUE TITLE
Subtitle output from Whisper models

### ISSUE THREAD

**Issue by pricklygorse** [mkiol/dsnote#55]
Whisper is able to output VTT and SRT subtitle files automatically. Could this be added as an option? Or if the model is already outputting them, where are they saved? Thanks!

**Comment by mkiol** [comment]
Thanks you for your question.

Unfortunately subtitle generation has not been implemented yet.

Support for "subtitles" would be  a valuable feature both for STT (audio=>subtitles) and TTS (subtitles=>audio). 

I'm adding this to my to-do list.

**Comment by mkiol** [comment]
Changes:

 - SRT subtitles generation for STT: 970ebe0f49d43e1f948ece3b1430bcb313684b2c
- Respecting SRT timestamps in TTS: 93842ab4e5e7d346740442d07cc6d37a892ff8b1 5ff9079c4115a24ef33405cc5010e91a8fdff266

Changes are included in v4.4.0.
