### ISSUE TITLE
Configure audio source

### ISSUE THREAD

**Issue by alexschneider** [mkiol/dsnote#57]
~~I'd like to be able to configure my audio source as I have multiple microphones and some may be more optimal than others. In addition, I'd also like to be able to use monitors as a source, so that I can transcribe what is coming through my speakers. ~~

I fail at reading. It's already a setting. Mea culpa

**Comment by DivineMK** [comment]
I want to add on to this issue @mkiol because I can't find the audio sources which is my laptop speaker. It seems it is not included as shown below:
![image](https://github.com/mkiol/dsnote/assets/42614396/ae16e386-538d-412e-baeb-c97ca1012be6)

**Comment by mkiol** [comment]
@DivineMK This option let you choose microphone (or other audio source) used in speech to text. In my system, all microphone names start with `alsa_input`. A value of "Auto" means that the default microphone is used.

In my opinion, it is most convenient to stay with the `Auto` option and decide which microphone is default in your OS settings. For instance, in KDE Plasma you just click on system tray and choose the default speaker and microphone. Most likely in GNOME there is something similar.

![image](https://github.com/mkiol/dsnote/assets/1420902/1e9d5ffb-7094-4b17-b371-c3452954f7b2)

**Comment by DivineMK** [comment]
I see. Is it possible to use the audio from the laptop instead of microphone? Because I want to use it for live captioning my lecture.

**Comment by mkiol** [comment]
Alright! Now I understand :) You mentioned a "laptop speaker", but I thought you meant a microphone.

Excellent question because this option is for exactly that purpose. Most likely you should choose one of Sink Monitor source. This should be Sink Monitor of audio output which is used for default audio playback in your OS. In my system it is "alsa_output.pci-0000_0a_00.4.analog-stereo.monitor".

**Comment by DivineMK** [comment]
Ohh I see I managed it now thank you! I'm a bit curious what command do you use to check the available inputs?

**Comment by mkiol** [comment]
Speech Note fetches these weird names form Qt Audio API.  It appears that on Linux Qt just wraps Pulse Audio interface, so you can list all PA sources with `pactl list sources`.

**Comment by DivineMK** [comment]
Ahhh I see!
