### ISSUE TITLE
Flathub description has wrong verb tense and no article before network connection.

### ISSUE THREAD

**Issue by ZMensRain** [mkiol/dsnote#6]
Speech Note enables you to take and read notes with your voice with multiple languages. It uses Speech to Text and Text to Speech conversions to do so. All voice processing is entirely done off-line, locally on your computer without the use of **network connection**. Your privacy is always respected. No data is **send** to the Internet.
### It should be 
**a network connection**
**sent**

**Comment by mkiol** [comment]
Thanks for letting me know.

Resolved in 8fa10cae8d6ea1620a242279d3ad5782fcb1d867.
