### ISSUE TITLE
It is hard to see what the "Download" button corresponds to in the model download dialogue 

### ISSUE THREAD

**Issue by muelli** [mkiol/dsnote#60]
On my screen, I cannot easily see what line the buttons on the right correspond to, i.e. what I am downloading.

![image](https://github.com/mkiol/dsnote/assets/322807/a74b5e97-dd43-4a11-a3a1-bd09346c8510)

Also, it would be nice to have a small indication about the size that's being downloaded before pushing the button.

**Comment by mkiol** [comment]
Thanks for the report.

Indeed, it doesn't look good.

Adding to TO-DO for 4.4.0 release.

**Comment by mkiol** [comment]
Fixed in v4.4.0
