### ISSUE TITLE
Stop button smaller than cancel 

### ISSUE THREAD

**Issue by muelli** [mkiol/dsnote#61]
![image](https://github.com/mkiol/dsnote/assets/322807/9c6b2ed8-c796-42e8-91c5-d2b40e756bff)

Look at this tiny stop button compared to the Cancel button.
I would go as far as assuming that "Stop" is the action for the vast majority of users and "cancel" the exception.
I would hence expect that the "Stop" button is much much bigger (and hence easier to reach and operate) than the cancel button. I believe the current behaviour violates Fitts Law.

My suggestion is to rework the "Listen" button to double as a "stop" button and to have a small, icon-only, cancel button right next to it.
This is one of the very very few cases where I would consider a modal dialogue, blocking further interaction with the app until the recording is stopped or cancelled.
One could even think about not having a cancel button at all at this stage and postpone the cancellation to when the recording has been obtained, i.e. to cancel the post-processing.

**Comment by mkiol** [comment]
It makes sense. I noted your suggestion and will try to improve it in the next release.

I must admit that implementing UI is a constant pain for me.

**Comment by devSJR** [comment]
@mkiol do not worry. This is a pain for most developers. But it can be fun if the community is constructive and rewarding.

**Comment by mkiol** [comment]
"Bigger stop button" added in 74e6c7737702cb2f54c730a71b10bcf22d4813a9.

Change is included in v4.4.0.
