### ISSUE TITLE
Limit the number of CPU cores

### ISSUE THREAD

**Issue by devSJR** [mkiol/dsnote#62]
The tool can use all the CPU cores to perform certain things like translating texts. Of course, that makes it fast. In some situations, however, it is not advantageous, especially if you have a very long, comprehensive text. In this case, all cores are used, and the system is sluggish. It would be helpful if defined how many CPU cores may be used by the app (default, all) to make sure you still have enough computing power to perform other tasks.

P.S.: The app is just great! Thanks.

**Comment by mkiol** [comment]
Thank you for noticing this 👍🏿 

I will add an option for this.

**Comment by mkiol** [comment]
6f7f4ad34732696b358697b40a49d90f5629b2fb
