### ISSUE TITLE
[Request] Start And Minimize To Tray

### ISSUE THREAD

**Issue by hbednar** [mkiol/dsnote#67]
Can you please give users the ability to start Speech Note in the system tray instead of opening the window and the option to minimize to the tray instead of leaving the window open.

**Comment by mkiol** [comment]
Thanks for the idea. Adding to TO-DO list.

**Comment by mkiol** [comment]
Added in: a46f8643a189142421b21beb79d7e6dab4538de5

Change is included in v4.4.0.
