### ISSUE TITLE
Dsnote saves the last spoken text - Privacy

### ISSUE THREAD

**Issue by devSJR** [mkiol/dsnote#76]
The app has the useful property to save the last spoken text or noted text until the next start. 
However, this could also be a disadvantage for a few users, since confidential information may be contained, and you do not want it to be saved there.
Therefore, I would recommend having an option where the text is saved by default. Additionally, there should be an option to delete information when ending the program.

**Comment by mkiol** [comment]
> Therefore, I would recommend having an option where the text is saved by default. Additionally, there should be an option to delete information when ending the program.

Thanks. I like this idea 👍🏿  Adding to TO-DO list.

**Comment by mkiol** [comment]
Added in: 5ab941f83e7a916653deb12ff9c719ba77612f9b

**Comment by mkiol** [comment]
Included in v4.5.0:

- Settings option to enable/disable remembering the last note. If the option is disabled, the last note will not be available after restarting the app.
