### ISSUE TITLE
Feature request: Files with multiple audio tracks

### ISSUE THREAD

**Issue by road2react** [mkiol/dsnote#78]
Some audio/video files can have multiple audio tracks. It would be useful to be able to select which audio track(s) to use to transcribe from, without having to manually downmix the tracks into a single file.

**Comment by mkiol** [comment]
Thanks for the report.

Adding to TO-DO list.

**Comment by mkiol** [comment]
Added in: 87a244dfa3589ccf8630e4144797aeffdf3b2032

Change is included in v4.4.0.
