### ISSUE TITLE
Speech Notes cant start on my Debian 12 KDE

### ISSUE THREAD

**Issue by dCo3lh0** [mkiol/dsnote#79]
Here is the log:
`qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
`

since it could not initialize GLX, i looked around and i found that this environment variable here somehow bypasses a little of the problem:
`export QT_XCB_GL_INTEGRATION=none`
or
`export QT_XCB_GL_INTEGRATION=xcb_egl`

but the problem persists since I suspect it's the libGL drivers causing this issue.

**Comment by dCo3lh0** [comment]
I have a RTX 2060 properly installed with latest drivers here and cuda working on my debian. version 545.23.08, CUDA 12.3

**Comment by mkiol** [comment]
Thanks for the report.

Could you please run the app with `--verbose` option as follows to collect more logs:

```
flatpak run net.mkiol.SpeechNote --verbose
```

In one more test, please try to disable any GPU support with `--gpu-scan-off`

```
flatpak run net.mkiol.SpeechNote --verbose --gpu-scan-off
```

**Comment by dCo3lh0** [comment]
same result, same log, nothing different.

**Comment by mkiol** [comment]
The app appears to crash before any logging functions are initiated 🤔 

Honestly, I don't have any clue what could be wrong. While searching the Internet, I found [this](https://github.com/flathub/com.calibre_ebook.calibre/issues/120) issue report. The problem looks similar and the cause was incorrect Flatpak GPU driver version.

Can you check the version of the driver in your system and the version in the flatpak? Maybe there is a mismatch.

For instance, in my system installed NVIDIA driver is "545.29.06" and I have also installed flatpak driver "org.freedesktop.Platform.GL.nvidia-545-29-06". Both drivers are compatible.

**Comment by dCo3lh0** [comment]
just found the problem on this package repo on flathub github page, seems this will be a problem specific for this release

https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/pull/214

**Comment by dCo3lh0** [comment]
there isn't a package for this version "org.freedesktop.Platform.GL.nvidia-545-23-08" so therefore it can only be solved in the next update from nvidia cuda repos.

**Comment by dCo3lh0** [comment]
or i could install nvidia-alternative drivers that points to 545-23-06 which has package in flathub, but i would had to reinstall everything, such a pain.

**Comment by mkiol** [comment]
Thanks for letting know 👍🏿  I'm glad you found the cause.

**Comment by klaus3981** [comment]
> Thanks for the report.
> 
> Could you please run the app with `--verbose` option as follows to collect more logs:
> 
> ```
> flatpak run net.mkiol.SpeechNote --verbose
> ```
> 
> In one more test, please try to disable any GPU support with `--gpu-scan-off`
> 
> ```
> flatpak run net.mkiol.SpeechNote --verbose --gpu-scan-off
> ```

The last one worked for me. What does follow from that?
