### ISSUE TITLE
Speech Note dont start on Linux Mint 20.3

### ISSUE THREAD

**Issue by fnieto24** [mkiol/dsnote#80]
franklin@HP-Microtower:~$ flatpak run net.mkiol.SpeechNote
Gtk-Message: 09:14:02.694: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Could not open network socket
ALSA lib ../../oss/pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib ../../../src/pcm/pcm_direct.c:2045:(snd1_pcm_direct_parse_open_conf) The field ipc_gid must be a valid group (create group audio)
ALSA lib ../../../src/pcm/pcm_direct.c:2045:(snd1_pcm_direct_parse_open_conf) The field ipc_gid must be a valid group (create group audio)

**Comment by fnieto24** [comment]
please can somebody help? what can I do? thank

**Comment by mkiol** [comment]
Thanks for the report.

Could you please run the app with `--verbose` option?

```
flatpak run net.mkiol.SpeechNote --verbose
```

**Comment by mkiol** [comment]
If the problem still occurs, please re-open.
