### ISSUE TITLE
is there anyway to use this from the cli?

### ISSUE THREAD

**Issue by ralyodio** [mkiol/dsnote#83]
or does it have to be via the gui? I'd like to run this on my server and provide an api endpoint if possible.

**Comment by mkiol** [comment]
This is primary a GUI app. It is not intended for use from cli. 

If you are looking for something that can be nicely integrated on a server side, I recommend you to check the following projects (sub-components of Speech Note):

STT:
- https://github.com/ggerganov/whisper.cpp

TTS:
- https://github.com/rhasspy/piper
- https://github.com/coqui-ai/TTS

**Comment by mkiol** [comment]
The question has been answered

**Comment by cirosantilli** [comment]
Sad. This could likely be done with just a bit of extra code to do text to mp3 given that it is all already possible on GUI.

I've gotten as far as:

```
flatpak run net.mkiol.SpeechNote \
  --id en_coqui_fairseq_eng \
  --text 'Hello, my name is John Smith. What is your name?' \
  --action start-reading-text
```

is there any action to export to file like in GUI rather than read?

Then just need something to not open GUI.

And something that does not require going to GUI to enable actions.

For my research at: https://askubuntu.com/questions/501910/how-to-text-to-speech-output-using-command-line/1522885#1522885

**Comment by mkiol** [comment]
@cirosantilli 
Thanks for the question.

The CLI interface is primary for the integration with the desktop **when Speech Note is already running** (for example, hidden in the system tray). Speech Note would be a very bad tool to use only through the CLI, as it is veeeery slow at startup. 

> is there any action to export to file like in GUI rather than read?

Unfortunately, at the moment there is no option to export to file via CLI. I will think about adding it to a future version.

**Comment by cirosantilli** [comment]
Yes, slow startup is an issue with several speech models that I've tested. However even at slow startup there can be CLI-only value if you're doing larger chunks of text from time to time for example.

**Comment by SuperCowProducts** [comment]
> [@cirosantilli](https://github.com/cirosantilli) Thanks for the question.
> 
> The CLI interface is primary for the integration with the desktop **when Speech Note is already running** (for example, hidden in the system tray). Speech Note would be a very bad tool to use only through the CLI, as it is veeeery slow at startup.
> 
> > is there any action to export to file like in GUI rather than read?
> 
> Unfortunately, at the moment there is no option to export to file via CLI. I will think about adding it to a future version.

Yes, I think the strength of this app is that it allows quick testing of a good selection of TTS / STT engines, and you just click a button and they're ready to go, as opposed to installing each one manually through CLI, which becomes a lot more fiddly and error-prone.

Once audio file input / text output and viceversa is ready on the CLI this could be integrated in practically any automated workflow, which for someone who regularly uses this technology is quite the lifesaver at times.

**Comment by ralyodio** [comment]
I have all sorts of use cases if it can run server side via cli
