### ISSUE TITLE
Change clean symbol for waste bin

### ISSUE THREAD

**Issue by devSJR** [mkiol/dsnote#87]
I would recommend that in the interface, the icon for delete (wide brush) be replaced by a recycle bin icon. Typically, this brush is always used as an icon for the transfer of formatting (at least in Office applications). Maybe that's a bit more consistent for many users.

**Comment by mkiol** [comment]
The actual icon might depend on theme installed in your system. 

In Speech Note, all "Delete" buttons use "edit-delete-symbolic" icon. 

On my system (Plasma) it looks not so bad, "red trash bin":

![image](https://github.com/mkiol/dsnote/assets/1420902/2ff5e36b-0919-4ae0-84e3-af221358144a)

**Comment by devSJR** [comment]
Sorry for the confusion. I mean in the input interface where people can copy, paste and delete something after I have spoken text or something like that.
 Will add a screenshot later (if needed).

**Comment by mkiol** [comment]
Ooh, this icon. Indeed, it can be misleading.

Changed in 0267cab465c66b51782863a70afc4e8b39dfaecd.

Thank you for noticing this.
