### ISSUE TITLE
How to know how much storage space I'm using for downloaded models etc...

### ISSUE THREAD

**Issue by seth100** [mkiol/dsnote#89]
As on the title, I installed the Flatpak version and was wondering about the location of the downloaded models and that it could be a good idea to add to the UI a view where to see the total size of downloaded files!

Thanks, great work BTW!!!

**Comment by mkiol** [comment]
Thanks for the question. 

In upcoming 4.4. version there is "Model Info" page, where you can check the size of all files that needs to be downloaded.

![image](https://github.com/mkiol/dsnote/assets/1420902/6f905b72-ea28-429f-998b-50012625824b)

If you want to try it, you can install beta version from [flathub-beta](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) channel.

**Comment by seth100** [comment]
Oh cool, thanks. And can you tell me where to find the downloaded files on the system storage so that I can check there until the new year version will be released?

**Comment by mkiol** [comment]
In Flatpak package, the default location is:
~/.var/app/net.mkiol.SpeechNote/cache/net.mkiol/dsnote/speech-models

You can change it in `Settings`->`Other`->`Storage`->`Location of language files`.
