### ISSUE TITLE
French translation (of the gui)

### ISSUE THREAD

**Issue by LAfricain** [mkiol/dsnote#9]
Some parts of Speechnote are note well translated.
I would like to help. I forked the git. Can I just use git, or do you have an other tool for translation?

**Comment by mkiol** [comment]
Awesome :)

Whatever you like. You can contribute via [transifex](https://app.transifex.com/mkiol/dsnote/language/fr) or directly via PR. Both ways are fine. 

Just be aware that [translation file](https://github.com/mkiol/dsnote/blob/main/translations/dsnote-fr.ts) also contains few strings that are only for phone app (Sailfish OS). Hopefully it is not a problem.

**Comment by LAfricain** [comment]
On transifex it's perfect. Did you see the strange string in the Settings (with &):
![settings](https://github.com/mkiol/dsnote/assets/19690477/1ceaa1e5-9807-480c-83c5-2b8cb261eed5)

**Comment by LAfricain** [comment]
> Awesome :)

Your work is awesome :) thank you for this software.

**Comment by mkiol** [comment]
> Did you see the strange string in the Settings (with &)

Oh no! I did not. Thank you for noticing it. Just tested and (fortunately or unfortunately) only French is affected. It looks I messed something up in translation compilation. 

BTW, translation on transifex is fine, feel free to contribute :)

**Comment by LAfricain** [comment]
Please internalize in languages: "Type to search", All models, Only speech to text... Close
And "Say something..."

**Comment by mkiol** [comment]
Ohh, thanks for checking. 

Just uploaded updated file to transifex.

**Comment by LAfricain** [comment]
Perhaps we could also add the version modification windows to be translated?

**Comment by mkiol** [comment]
> Perhaps we could also add the version modification windows to be translated?

 I think it would be too cumbersome for the translators (including You). I going to change "the changelog" very frequently and believe it would be painful. My priority is to keep translators happy :)

Thank you for your contribution. I'm releasing new version today.

**Comment by LAfricain** [comment]
I was not thinking to translate all, but only the "Interface", Speech to text"... (the titles)
