### ISSUE TITLE
GUI feature request 

### ISSUE THREAD

**Issue by lamyergeier** [mkiol/dsnote#91]
![image](https://github.com/mkiol/dsnote/assets/42092626/4d8e00fb-b3d9-4052-96f9-26d41e544e3d)

As shown in the above image:

1. Top Bar Menu items are not shown fully (F....)
2. Change the speed of Read, if already started is not possible.
3. How to change the Font size? 
4. Support dark more (for example, Solarized Dark and Solarized Light)

**Comment by mkiol** [comment]
> Top Bar Menu items are not shown fully (F....)

Oh no! What is your system? OS, DE?

> Change the speed of Read, if already started is not possible.

Unfortunately it works like that. It will be difficult to change it. Speed parameter is a property of TTS model, therefore any change requires re-run of speech synthesis.

> How to change the Font size?

There is an option in _Settings_ -> _Font size in text editor_

> Support dark more

In theory, dark theme should work. It definitely works on KDE Plasma. To make it work on GNOME you probably have to install some KDE libs and switch theme in the system. To be honest, I still haven't fully figured out how theming works in Qt apps in GNOME (+ Flatpak). It is a misery to me...

Regarding other themes ("Solarized Dark and Solarized Light"), I don't know if it possible. Speech Note for theming uses so called "QQC2 Style". Few styles are already installed in a Flatpak runtime and you can switch between them using option in the Setting (_Use custom graphic style_ -> _Graphical style_). Most likely it is not what you are looking for.

**Comment by lamyergeier** [comment]
> What is your system? OS, DE?

Fedora 39 (Gnome, Wayland)

**Comment by lamyergeier** [comment]
> Unfortunately it works like that. It will be difficult to change it. Speed parameter is a property of TTS model, therefore any change requires re-run of speech synthesis.

In Firefox we can change the speed of "Read" while it is running (without having to stop and start

**Comment by mkiol** [comment]
> Top Bar Menu items are not shown fully (F....)

I wanted to reproduce this problem. On fresh Fedora 39 GNOME, the app looks decent. Did you make any significant changes in desktop settings?

![Screenshot from 2024-01-27 19-23-27](https://github.com/mkiol/dsnote/assets/1420902/20becb71-d59b-4244-8014-ceaf31a41f02)

**Comment by lamyergeier** [comment]
After I checked again it looks fine. I don't know why it showed up like that the last time. I can't reproduce that again. I haven't modified my Fedora much beyond standard option available in the official settings.
--

Thanks and Regards

Lamy
----------------------------------------

Jan 27, 2024 19:37:43 mkiol ***@***.***>:

**Comment by mkiol** [comment]
I think this problem is already solved.
