### ISSUE TITLE
Add more Arabic models

### ISSUE THREAD

**Issue by Kentoseth** [mkiol/dsnote#94]
There is a site that hosts Arabic models here: https://arbml.github.io/masader/

Some **translation** models can be found there for various Arabic dialects.

There is also: https://clartts.com/

> Open-Source Classical Arabic Text-to-Speech Dataset 

Although the sum of users for this model would be low, its usage is valuable in the academic space.

**Comment by mkiol** [comment]
Thanks! I will definitely check out these resources.

> There is also: https://clartts.com/

Unfortunately, actual model is not available yet (or I missed something). There is only corpus (raw wav files) and vocoder to download. Maybe they will release rest of the system soon.

**Comment by Kentoseth** [comment]
> Unfortunately, actual model is not available yet (or I missed something). There is only corpus (raw wav files) and vocoder to download. Maybe they will release rest of the system soon.

sorry about that. Here is the link to the model: https://huggingface.co/MBZUAI/ArTST/tree/main

I was told the model to use is: CLARTTS_ArTSTstar_TTS.pt

I'm not sure if it's in the right format though. But this is the fine-tuned option.

**Comment by mkiol** [comment]
Thanks.

Unfortunately this ArTST model is not compatible with any TTS engines that are currently integrated. I would have to wrap ArTST code as a new engine which is a lot of work, especially just for one language. Is this model particularly special? If so, maybe that would justify the effort.

BTW, Have you tried Coqui XTTS (both v2.0.2 and v2.0.3? How good is this model in Arabic?

**Comment by Kentoseth** [comment]
> Unfortunately this ArTST model is not compatible with any TTS engines that are currently integrated.

That would be an up-stream problem that I should discuss with them to make the model functional in down-stream engines.

> Is this model particularly special?
> Have you tried Coqui XTTS (both v2.0.2 and v2.0.3? How good is this model in Arabic?

This is a very good question. From the demo, I would say ArTST is okay-ish. But with XTTS, ArTST may even be obsolete. I will test XTTS locally to see how it fairs against ArTST.

**Comment by Kentoseth** [comment]
I'm closing this to test Coqui instead.
